### ISSUE TITLE
Add progressbar for XML serializer

### ISSUE THREAD

**Issue by Stinkfist0** [IfcOpenShell/IfcOpenShell#122]
There's seems to be a really long pause (can be tens of seconds, maybe even minute, depending how large the file is) between "Done scanning file" and "Creating geometry..." phases. Should maybe be inspected if there is a real performance issue somewhere here.

**Comment by aothms** [comment]
Could it be because of: https://github.com/IfcOpenShell/IfcOpenShell/commit/562f38756f8f2d2ecea8879112019d10dd9a2154 Maybe we need to check first if `--center-model` is set prior to iterating over all product placements.

A minute sounds like a whole lotta time for processing the product placements too. Maybe there is still something left to optimize there.

**Comment by aothms** [comment]
@Stinkfist0 I tried this on `DC_Riverside_Bldg-LOD_300.ifc` (279mb) and I cannot observe anything beyond a fraction of a second. Are we talking about much larger files here, something you can share perhaps?

**Comment by Stinkfist0** [comment]
I'll try to dig up some files to test again this.

**Comment by Stinkfist0** [comment]
OK, so revisiting this, and this issue can be observed writing an XML output for a file that has a lot of property (and layer) information, so maybe at least add a simple progress print for that.

**Comment by aothms** [comment]
Ok!

**Comment by Moult** [comment]
PR seems to be merged, so this is solved and can be closed?

**Comment by aothms** [comment]
Well we still don't have a progress bar.

> OK, so revisiting this, and this issue seem to be present when writing an XML output for a file that has a lot of property (and layer) information, so maybe at least add a simple progress print for that.

This is likely just the inefficiencies for calculating inverses we suffered from at the time.
