### ISSUE TITLE
Bug report: fail at parsing IFC4x1 standard files

### ISSUE THREAD

**Issue by tpaviot** [IfcOpenShell/IfcOpenShell#1311]
current ifcopenshell v0.6.0 fails at parsing example IFC files provided with the IFC4X1 standard (for example https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/annex/annex-e/wall-elemented-case.ifc). I ran the tests using python and the ```ifcopenshell.open``` function.

In these Part 21 files, the file schema is defined as:
```FILE_SCHEMA('IFC4x1')```
with a lowercase 'x' whereas ifcopenshell expects an uppercase 'X' (just changing the 'x' to 'X' makes it succeed).

A fix should target the following points:
* accept both lowercase/uppercase schema names (even ```iFc4x1``` should pass),
* raise an explicit exception if ever the schema name is not supported.

**Comment by aothms** [comment]
You're right, I think for the first we can simply change `name` to `boost::to_upper_copy(name)` https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcparse/IfcSchema.cpp#L93

The second pertains the try catch scheme here which is indeed messy https://github.com/IfcOpenShell/IfcOpenShell/blob/37fe54d2476d9cf3e74998f533035c68cb30eb3f/src/ifcparse/IfcParse.cpp#L1370

One of the problems is that these Logger Messages don't really propagate well to python. Maybe that's what we should do? Somehow map (some of the Logger Messages) in logger.cpp to std::exceptions that are then caught by SWIG?

**Comment by tpaviot** [comment]
yes, ```boost::to_upper_copy``` would certainly work.

For the second point, throwing c++ exceptions caught by swig would indeed to the job. It is how pythonocc catch occt exceptions:
https://github.com/tpaviot/pythonocc-core/blob/master/src/SWIG_files/common/ExceptionCatcher.i#L37

You can also return either true/false in the cpp open method, and raise IOError in the python wrapper if open returns false.

**Comment by aothms** [comment]
Yes we have something similar https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcwrap/IfcPython.i#L59

> return either true/false

We have the .good() test for that. An indeed an exception is already thrown in case it returns false https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcopenshell-python/ifcopenshell/__init__.py#L63

Are you saying that didn't work in your case? Or are you saying (which was my interpretation) we should make the return from good() more informed: unable to read, no valid spf header, unsupported schema, ...

**Comment by tpaviot** [comment]
Sorry for not being explicit enough. Here is the current trace I get:
```
Traceback (most recent call last):
  File "ifc_load_standard_example_IFC4X1.py", line 61, in <module>
    ifc_file = ifcopenshell.open(ifc_filename)
  File "/home/thomas/miniconda3/envs/occt750/lib/python3.7/site-packages/ifcopenshell/__init__.py", line 63, in open
    raise IOError("Unable to open file for reading")
OSError: Unable to open file for reading
```
I would expect something like:
``` raise IOError("IFC4x1 is not supported. Schema must be either IFC4X1, IFC3 etc.```

The "unable to open file for reading" log message is too general.  I first suspected problems with geometry conversions, or a wrong filename, before I finally understand that the problem comes from the schema name.

**Comment by aothms** [comment]
I think both things are addressed now with both commits

**Comment by tpaviot** [comment]
Absolutely, successfully tested.

**Comment by fclairec** [comment]
Hi, It sems that the pre-built versions 0.6.0 (I tired python 36 and 39) on the webpage still don't have this fix included. Is there any chance you could update this? 
Thanks a lot.

**Comment by aothms** [comment]
@fclairec I've updated the website to point to 721fe4729aa5302efe1602971aae2558934ad098 for 0.6
