### ISSUE TITLE
Bimtester: scenarios using stepmatcher

### ISSUE THREAD

**Issue by dedicos** [IfcOpenShell/IfcOpenShell#1594]
When checking for a property in a certain PSet (basically, every scenario that uses the regex stepmatcher) I get errors like this (or "not yet specified"). Also, there is a difference in the result depending on if the "a" at the beginning is in upper or lower case.

Scenario: Test 1
* all IfcWall elements have a Pset_WallCommon.Reference property
```
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\behave\model.py", line 1329, in run
match.run(runner.context)
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\behave\matchers.py", line 98, in run
self.func(context, *args, **kwargs)
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\bimtester\features\steps\attributes_psets\en.py", line 29, in step_impl
if not IfcStore.file.get_property(element, pset_name, property_name):
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\file.py", line 311, in __getattr__
"""
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 1427, in <lambda>
__getattr__ = lambda self, name: _swig_getattr(self, file, name)
File "C:\Users\abc\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 80, in _swig_getattr
raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'file' object has no attribute 'get_property'
```

**Comment by Moult** [comment]
@Nitschi recently submitted a PR to port these scenarios. The "a" currently is lowercase in the code, but we should fix it to be uppercase. Also, file.get_property doesn't exist. That code needs to be rewritten. The best way to rewrite it would be to use ifcopenshell.util.element.get_psets(element), which gives you a dictionary of psets and properties. Then you can just check for property names and pset names in the dictionary.

Would you like to help submit a PR? Code is here: https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcbimtester/bimtester/features/steps/attributes_psets/en.py

**Comment by dedicos** [comment]
I removed the dependency on "get_property". I still have an issue because I don't receive the property itself but a string. Can someone check that please? I'll go through it, too. As this was my first PR, anything I should consider?

**Comment by dedicos** [comment]
I fixed it (sorry to say, but I am a bit proud of myself for this my first bug fix ever ;) ). Checking property values by a regex pattern is now working.
#1596 should fix this issue

**Comment by Moult** [comment]
Thank you so much! I've merged the PR!
