### ISSUE TITLE
v0.7.0 get_inverse returns duplicates

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1747]
A little present from the test suite :)

```
>>> import ifcopenshell
>>> f = ifcopenshell.file()
>>> s = f.createIfcSite()
>>> o = f.createIfcOwnerHistory()
>>> s.OwnerHistory = o
>>> f.get_inverse(o)
[#1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$), #1=IfcSite($,#2,$,$,$,$,$,$,$,$,$,$,$,$)]
```

**Comment by aothms** [comment]
oh right, because we now reference them as a tuple of 3 we insert duplicates for every supertype. Hence I had to create another copy of the map for usage without inheritance which is used when you do not supply a type. Should be fixe

**Comment by Moult** [comment]
Unfortunately now I get a segfault (again courtesy of the test suite :) :(

```
import ifcopenshell
f = ifcopenshell.file()
e = f.createIfcWall(GlobalId="id")
r = f.createIfcRelAggregates()
r.RelatingObject = e
f.remove(e) # segfault
```

By the way, in `ifcopenshell-python` you can try `make test` assuming you have pytest installed.

**Comment by aothms** [comment]
> By the way, in ifcopenshell-python you can try make test assuming you have pytest installed.

Ah that's why. We're running `make test` on the 0.6 but not for 0.7. I had been meaning to ask. Guess I need to hurry up with the merge then.

**Comment by aothms** [comment]
> By the way, in ifcopenshell-python you can try make test assuming you have pytest installed.

Ah that's why. We're running `make test` on the 0.6 but not for 0.7. I had been meaning to ask. Guess I need to hurry up with the merge then.

Ok, merge is completed. And this 2nd issue is addressed. I'm going to wait for the ci tests to complete and then start IfcOpenBot.

**Comment by Moult** [comment]
So sorry I'm still seeing an issue:

```
import ifcopenshell
f = ifcopenshell.api.run("project.create_file")
p = ifcopenshell.api.run("owner.add_person", f)
o = ifcopenshell.api.run("owner.add_organisation", f)
u = ifcopenshell.api.run("owner.add_person_and_organisation", f, person=p, organisation=o) #3
ifcopenshell.api.owner.settings.get_user = lambda x : u
h = ifcopenshell.api.run("owner.create_owner_history", f)
print(f.get_inverse(u))
[#8=IfcOwnerHistory(#3,#7,.READWRITE.,.ADDED.,1633073105,#3,#7,1633073105), #8=IfcOwnerHistory(#3,#7,.READWRITE.,.ADDED.,1633073105,#3,#7,1633073105)]
```

In this case, you can see that `8` references `3` twice, which I think is what causes the inverse to double up.

**Comment by aothms** [comment]
Yes I kind of deliberately left that in. It's a change in behaviour from 0.6 though, but if you want to get the old behaviour back you can do `set(f.get_inverse(u))`. There might be some value in being able to do `f.get_inverse(u).count(f[8]) == 2`. Now that we have the possibility I didn't want to immediately erase it.

We can change the method to `get_inverse(allow_duplicate=False)` and if `not allow_duplicate` do the conversion to set() or list(set()) so that users get the behaviour they are used to.

**Comment by Moult** [comment]
Ah good idea! I'll change the python signature to default to the old behaviour but put a new kwarg as you suggest.

I reckon its better to default to the old behaviour since the vast majority of the time I use get inverse I think I'll prefer it off (e.g. replacing attributes,  or deleting). But good to have the new option :)

I'll close the bug when I get to a computer and can commit
