### ISSUE TITLE
python segfault

### ISSUE THREAD

**Issue by brunopostle** [IfcOpenShell/IfcOpenShell#2486]
I see this with 835e3f0, initially the problem manifested in blenderbim: create a new project, save, save again, crash.

I can reproduce with this short script:

```
#!/usr/bin/python3

import ifcopenshell.api

run = ifcopenshell.api.run

file = run("project.create_file")

mymaterial = run("material.add_material", file)
pset = run("pset.add_pset", file, product=mymaterial)
run(
    "pset.edit_pset",
    file,
    pset=pset,
    properties={"foo": "bar"},
)

another_file = run("project.create_file")

run(
    "project.append_asset",
    another_file,
    library=file,
    element=mymaterial,
)
```

stacktrace:

```
                Stack trace of thread 52217:
                #0  0x00007f76eb040bfd _ZN8IfcParse7IfcFileD1Ev (libIfcParse.so.0.6 + 0x2040bfd)
                #1  0x00007f76eb040f2d _ZN8IfcParse7IfcFileD0Ev (libIfcParse.so.0.6 + 0x2040f2d)
                #2  0x00007f76f08f99e4 _wrap_delete_file.lto_priv.0 (_ifcopenshell_wrapper.so + 0xf99e4)
                #3  0x00007f76f08868f8 SwigPyObject_dealloc (_ifcopenshell_wrapper.so + 0x868f8)
                #4  0x00007f76fe90ec4d dict_dealloc (libpython3.10.so.1.0 + 0x10ec4d)
                #5  0x00007f76fe929761 subtype_dealloc (libpython3.10.so.1.0 + 0x129761)
                #6  0x00007f76fe90ec4d dict_dealloc (libpython3.10.so.1.0 + 0x10ec4d)
                #7  0x00007f76fe929761 subtype_dealloc (libpython3.10.so.1.0 + 0x129761)
                #8  0x00007f76fe90ed37 free_keys_object (libpython3.10.so.1.0 + 0x10ed37)
                #9  0x00007f76fe90eb25 dict_dealloc (libpython3.10.so.1.0 + 0x10eb25)
                #10 0x00007f76fe9c06be module_dealloc (libpython3.10.so.1.0 + 0x1c06be)
                #11 0x00007f76fe906493 insertdict (libpython3.10.so.1.0 + 0x106493)
                #12 0x00007f76fe9c0342 finalize_modules (libpython3.10.so.1.0 + 0x1c0342)
                #13 0x00007f76fe9bf82a Py_FinalizeEx (libpython3.10.so.1.0 + 0x1bf82a)
                #14 0x00007f76fe9b1654 Py_RunMain (libpython3.10.so.1.0 + 0x1b1654)
                #15 0x00007f76fe97de8d Py_BytesMain (libpython3.10.so.1.0 + 0x17de8d)
                #16 0x00007f76fe43feb0 __libc_start_call_main (libc.so.6 + 0x3feb0)
                #17 0x00007f76fe43ff60 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x3ff60)
                #18 0x0000559f1b1f9095 _start (python3.10 + 0x1095)
```

**Comment by Moult** [comment]
This is only with the latest IOS build? I'm still on the old one and have been starting with a library template in the UI without crashes.

**Comment by brunopostle** [comment]
This is with IfcOpenShell compiled from 835e3f0, 5th October. I'm building the current head now, but there haven't been any c++ changes in the meantime. I have to roll-back to 2nd October to get a working IfcOpenShell.

**Comment by brunopostle** [comment]
It still crashes with the latest git. gbd says this:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f087e240bfd in IfcParse::IfcFile::~IfcFile (this=<optimized out>, this=<optimized out>) at /usr/src/debug/IfcOpenShell-0.7.0-0.1.20221008git.fc35.x86_64/src/ifcparse/IfcParse.cpp:2352
2352			delete entity;

**Comment by aothms** [comment]
This is fixed now. I think we still may see some more fallout of the memory related low level changes. I think this is due to #2471 now actually having files destructed caused some issues when copying simple type instances between files. Thanks for reporting.

**Comment by brunopostle** [comment]
Thanks, that fixes the python segfault, but I still see the segfault in blenderbim.

To reproduce: create a new project, save, save, segfault

Stacktrace:

```
                Stack trace of thread 25043:
                #0  0x00007fed5521783e _ZNK8IfcParse11declaration2isERKS0_ (libIfcParse.so.0.6 + 0x201783e)
                #1  0x00007fed55236f68 _ZN21IfcEntityInstanceData11setArgumentEmP8ArgumentN7IfcUtil12ArgumentTypeEb (libIfcParse.so.0.6 + 0x2036f68)
                #2  0x00007fed5aaf4260 _wrap_FileName_name.lto_priv.0 (_ifcopenshell_wrapper.so + 0xf4260)
                #3  0x00007fed9c11f698 cfunction_call (libpython3.10.so.1.0 + 0x11f698)
                #4  0x00007fed9c127c18 _PyObject_Call (libpython3.10.so.1.0 + 0x127c18)
                #5  0x00007fed9c118e75 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x118e75)
                #6  0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #7  0x00007fed9c10cf06 _PyObject_VectorcallTstate.lto_priv.5 (libpython3.10.so.1.0 + 0x10cf06)
                #8  0x00007fed9c18e977 object_vacall (libpython3.10.so.1.0 + 0x18e977)
                #9  0x00007fed9c18e851 PyObject_CallFunctionObjArgs (libpython3.10.so.1.0 + 0x18e851)
                #10 0x00007fed9c1903d9 property_descr_set (libpython3.10.so.1.0 + 0x1903d9)
                #11 0x00007fed9c109653 _PyObject_GenericSetAttrWithDict (libpython3.10.so.1.0 + 0x109653)
                #12 0x00007fed9c1091de PyObject_SetAttr (libpython3.10.so.1.0 + 0x1091de)
                #13 0x00007fed9c113350 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x113350)
                #14 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #15 0x00007fed9c112bd0 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x112bd0)
                #16 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #17 0x00007fed9c112bd0 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x112bd0)
                #18 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #19 0x00007fed9c127778 method_vectorcall (libpython3.10.so.1.0 + 0x127778)
                #20 0x00007fed9c112759 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x112759)
                #21 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #22 0x00007fed9c1179e6 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x1179e6)
                #23 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #24 0x00007fed9c127778 method_vectorcall (libpython3.10.so.1.0 + 0x127778)
                #25 0x00007fed9c1179e6 _PyEval_EvalFrameDefault (libpython3.10.so.1.0 + 0x1179e6)
                #26 0x00007fed9c111590 _PyEval_Vector (libpython3.10.so.1.0 + 0x111590)
                #27 0x0000560c43d4237d bpy_class_call (blender + 0x18f637d)
                #28 0x0000560c43cffc32 rna_operator_invoke_cb (blender + 0x18b3c32)
                #29 0x0000560c437d8ea8 wm_operator_invoke.part.0.lto_priv.0 (blender + 0x138cea8)
                #30 0x0000560c437da565 wm_operator_call_internal.part.0.lto_priv.0 (blender + 0x138e565)
                #31 0x0000560c437ddd2c WM_operator_name_call_ptr (blender + 0x1391d2c)
                #32 0x0000560c443cc8eb ui_apply_but_funcs_after.lto_priv.0 (blender + 0x1f808eb)
                #33 0x0000560c44400eed ui_handler_region_menu (blender + 0x1fb4eed)
                #34 0x0000560c437dac35 wm_handlers_do_intern (blender + 0x138ec35)
                #35 0x0000560c437db8dd wm_handlers_do (blender + 0x138f8dd)
                #36 0x0000560c437dcd4c wm_event_do_handlers (blender + 0x1390d4c)
                #37 0x0000560c437df8f0 WM_main (blender + 0x13938f0)
                #38 0x0000560c43260b1b main (blender + 0xe14b1b)
                #39 0x00007fed9b83feb0 __libc_start_call_main (libc.so.6 + 0x3feb0)
                #40 0x00007fed9b83ff60 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x3ff60)
                #41 0x0000560c432a87d5 _start (blender + 0xe5c7d5)
```

gdb output:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  IfcParse::declaration::is (this=<optimized out>, decl=...) at /usr/src/debug/IfcOpenShell-0.7.0-0.2.20221008git.fc35.x86_64/src/ifcparse/IfcSchema.cpp:29
29		if (this->as_entity()) {
```

**Comment by brunopostle** [comment]
Some more investigation of this segfault: It is caused by a recent change to IfcOpenShell text string handling, in particular I can avoid the crash if I comment out this line in blenderbim:
[blenderbim/bim/export_ifc.py:77](https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/export_ifc.py#L77)

I can reproduce simply like so (`junk.ifc` is any existing ifc file):

```
$ python
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ifcopenshell
>>> file = ifcopenshell.open("junk.ifc")
>>> file.wrapped_data.header.file_name.name = "myfile.ifc"
Segmentation fault (core dumped)
```

**Comment by aothms** [comment]
Thanks, very helpful, bug introduced after #1861. Fixed now.

**Comment by aothms** [comment]
@Moult is there any reason you do `self.file.wrapped_data.header` and not `self.file.header`?

**Comment by Moult** [comment]
No reason, maybe when I first learned of the header I only found it in wrapped data.

**Comment by Moult** [comment]
Ah I guess I was tabbing to autocomplete and autocomplete only found it on wrapped_data.

**Comment by brunopostle** [comment]
Closing as fixed
