### ISSUE TITLE
BlenderBim - IfcSlab will not regenerate properly after editing if not all elements are selected

### ISSUE THREAD

**Issue by Plae-Blue-Dot** [IfcOpenShell/IfcOpenShell#2585]
IfcSlab will not regenerate properly after editing if not all elements are selected

IfcSlab:

![image](https://user-images.githubusercontent.com/78321676/201073475-d09a504a-c719-411b-99b6-78d9736dafeb.png)

IfcSlab after pressing shift-e
![image](https://user-images.githubusercontent.com/78321676/201073539-dd70cfb6-06ba-4588-a5a8-ce7a03dcef49.png)

Editing layout:
![image](https://user-images.githubusercontent.com/78321676/201073701-e655adac-884a-43e5-8113-a3f33fb73ef8.png)

Only 1 edge selected Shift-Q
![image](https://user-images.githubusercontent.com/78321676/201073944-ae76ced7-75c7-471f-9b66-48d13824643b.png)
Object geometry dissappears

All elements selected 
![image](https://user-images.githubusercontent.com/78321676/201074203-971cf791-209e-4e01-9c31-8165d7919c4b.png)

All elements selected Shift-Q (works as expected)
![image](https://user-images.githubusercontent.com/78321676/201074283-9e39a66f-1c05-43b5-8c86-7f2a5c5d9971.png)

Secondary issue, the IfcSlba FLR150  is actually 200mm deep not 150

And the IfcSlab FLR250 is 300mm deep

I'm sure that's just a wrong value somewhere

**Comment by Moult** [comment]
I cannot recreate this, do you have any other add-ons enabled? Can you try with factory settings?

**Comment by Plae-Blue-Dot** [comment]
> I cannot recreate this, do you have any other add-ons enabled? Can you try with factory settings?

I reset to factory settings and it seemed to fix it, I only have 2 other addons enabled, Cad transform & screencast keys

I've been getting it pretty consistently, I'll try to get a file that has the issue and upload

**Comment by Moult** [comment]
OK its probably a legitimate bug due to some circumstance not an add-on clash. I'll peek in the code tomorrow to see if I can guess what its related to but if you do manage to reproduce it reliably that would be a huge help :)

**Comment by theoryshaw** [comment]
haven't been able to replicate consistently yet, but when it does happen, i get this error...

```Python: Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\ifc.py", line 105, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\ifc.py", line 418, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\bim\module\model\slab.py", line 667, in _execute
    blenderbim.core.geometry.switch_representation(
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\core\geometry.py", line 99, in switch_representation
    data = geometry.import_representation(obj, representation)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\tool\geometry.py", line 181, in import_representation
    shape = ifcopenshell.geom.create_shape(settings, element)
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\geom\main.py", line 210, in create_shape
    ifcopenshell_wrapper.create_shape(settings, inst.wrapped_data, repr.wrapped_data if repr is not None else None),
  File "C:\Users\Owner\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\ifcopenshell_wrapper.py", line 2378, in create_shape
    return _ifcopenshell_wrapper.create_shape(settings, instance, representation)
RuntimeError: Failed to process shape

```

**Comment by Moult** [comment]
Has anyone been able to replicate this? I'm struggling to recreate it.

**Comment by Moult** [comment]
The moment someone gets this error message, can you save the .blend file (in this case I think it is critical) and maybe screenshot what the profile should've looked like? Certain things to pay attention to are whether there are any inner voids, arcs, or circles.

I suspect it is caused by Blender thinking the profile you've drawn is correct, when it is either invalid, or, it is valid, but it translates it incorrectly into IFC, which leads to that error.

**Comment by theoryshaw** [comment]
Test files: https://www.dropbox.com/sh/lxqc96boclz3bgm/AADs3HKgDZSgTgQ4X2Adp1V9a?dl=1
0.0.230126

**Comment by Moult** [comment]
@theoryshaw sorry that is a different bug to this one, caused by me forgetting a few things in this commit: https://github.com/IfcOpenShell/IfcOpenShell/commit/d69f6c02b620597a81f80ff691c3c593e838ff44 which has already been fixed by @myoualid https://github.com/IfcOpenShell/IfcOpenShell/commit/4af0c1c98ce02a38a6bfe7de6f7d402365df3f18

**Comment by theoryshaw** [comment]
I've pulled everything down, but still get this...
https://www.dropbox.com/sh/l4pait56911u97q/AAC0y_3azZbJq5LpU60hwwbQa?dl=1

no error, but geometry goes missing.

**Comment by Moult** [comment]
That's really weird and even weirder that you don't have thumbnails showing. I can't recreate it. Can we screenshare?

**Comment by theoryshaw** [comment]
yes, i should be around today... ping on the osarch channel.
