### ISSUE TITLE
Express rule validation issues

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#2685]
I thought I'd use this thread to cover various odd express rule validation results. Here's one, but there will be more coming so perhaps we can keep this thread open for a little bit.

When running validation on https://github.com/IfcOpenShell/IfcOpenShell/issues/2665 I get this:

```
2023-01-11 09:40:11,414    ERROR rule_executor.py 154 On instance:
    #22=IfcLocalPlacement($,#9)
Rule IfcLocalPlacement_WR21:
    IfcCorrectLocalPlacement(relativeplacement,placementrelto)
Violated by:
    None
     +  where None = IfcCorrectLocalPlacement(#9=IfcAxis2Placement3D(#6,#7,#8), None)
```

Shouldn't none be allowed?

**Comment by aothms** [comment]
I guess.

> A domain rule shall be asserted when the expression evaluates to a value of true; it shall be
> violated when the expression evaluates to a value of false; and it shall be neither violated
> nor asserted when the expression evaluates to a indeterminate (?) or unknown value.

So after my latest changes WR evaluation should result into False for an error to be triggered, not just python's "falsy".

> Here's one, but there will be more coming so perhaps we can keep this thread open for a little bit.

I'm eagerly awaiting... Thanks for testing.

**Comment by Moult** [comment]
Running on another model with IfcOpenBot build v0.7.0-6180d73f (with latest .py files from Github):

[test2.ifc.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/10410163/test2.ifc.txt)

```
    #133=IfcRelAssociatesMaterial('2xvXgaSvL7KPR25fXz0fSE',$,$,$,(#132),#136)
Rule IfcRelAssociatesMaterial_AllowedElements:
    ((sizeof([temp for temp in self.RelatedObjects if (sizeof(typeof(temp) * ['ifc4.ifcelement','ifc4.ifcelementtype','ifc4.ifcwindowstyle','ifc4.ifcdoorstyle','ifc4.ifcstructuralmember','ifc4.ifcport'])) == 0])) == 0)
Violated by:
    can't multiply sequence by non-int of type 'express_set'
2023-01-13 20:30:36,190    ERROR rule_executor.py 154 On instance:
    #199=IfcShapeRepresentation(#23,'Annotation','Annotation2D',(#198))
Rule IfcShapeRepresentation_CorrectItemsForType:
    (IfcShapeRepresentationTypes(self.RepresentationType,self.Items))
Violated by:
    can't multiply sequence by non-int of type 'express_set'
```

**Comment by aothms** [comment]
Cool, thanks, rather than waiting for a new openbotbuild I'd recommend you apply the changes textually awaiting any more issues you find.

**Comment by Moult** [comment]
Saw this today, not sure if it's already been solved, I'm just using the bot builds :)

```
2023-03-10 22:35:13,248    ERROR rule_executor.py 224 On instance:
    #1155=IfcIndexedPolyCurve(#1154,$,.F.)
Rule IfcIndexedPolyCurve.Consecutive:
    (sizeof(segments) == 0 or IfcConsecutiveSegments(segments))
Violated by:
    object of type 'NoneType' has no SIZEOF()
```

**Comment by aothms** [comment]
Hm, this rule was actually changed from:

    Consecutive : (SIZEOF(Segments) = 0) OR IfcConsecutiveSegments(Segments);

to

    Consecutive : NOT(EXISTS(Segments)) OR IfcConsecutiveSegments(Segments);


The standard says nothing specific about the behaviour of sizeof() on nil.

> ### 15.22 SizeOf - aggregate function
> 
>     FUNCTION SIZEOF ( V:AGGREGATE OF GENERIC ) : INTEGER;
> 
> The `sizeof` function returns the number of elements in an aggregate value.
> Parameters : V is an aggregate value.
> 
> Result:
> a. When V is an array the returned value is its declared number of elements in the aggregation
> data type.
> b. When V is a bag, list or set, the returned value is the actual number of elements in the
> aggregate value.

But

> All built-in functions will return an indeterminate (indeterminate (?)) result if passed an indeterminate
(indeterminate (?)) parameter unless explicitly specified otherwise in the description of the function.

So it should return indeterminate; indeterminate == 0 in turn is also indeterminate; indeterminate OR something is to be treated as unknown OR something; so IfcConsecutiveSegments will be evaluated; where HIINDEX(Segments) will return indeterminate; and a repeat loop body from or to indeterminate will not be evaluated; in the end actually returning true; passing the rule.

But thanks, this was a good one. Fixed quite a few things that were previously overlooked.

**Comment by Moult** [comment]
And here's one more which doesn't make sense to me:

```
2023-03-08:22:39:24,086 ERROR   [validate.py:396] For instance:

    #93181=IfcMaterialLayer(#37306,0.200000002980232,.F.,'','','',0)

With inverse:

    ToMaterialLayerSet : IfcMaterialLayerSet FOR MaterialLayers

Value:

    #93182=IfcMaterialLayerSet((#93181),'concrete',$)

Not valid
```

**Comment by aothms** [comment]
Can you double check with the latest validate.py? I guess this could happen with `ifcopenshell.settings.unpack_non_aggregate_inverses = True`, but that shouldn't happen. It's a bit of a struggle conforming to the express semantics while not breaking backwards compat.

**Comment by aothms** [comment]
@Moult

**Comment by Moult** [comment]
@aothms those were copy pasted from a user report so it's hard to replicate, but I did get their file and retry and I cannot replicate https://github.com/IfcOpenShell/IfcOpenShell/issues/2685#issuecomment-1469789674

I can however now see things like this:

```
For instance:
    #171705=IfcMaterialProfile($,$,#110867,#96769,$,$)
With inverse:
    ToMaterialProfileSet : IfcMaterialProfileSet FOR MaterialProfiles
Value:
    [
      1. #171703=IfcMaterialProfileSet($,$,(#171705),$)
      2. #171708=IfcMaterialProfileSet($,$,(#171705),$)
    ]
```

This one stood out because I've never seen the `[1:-1]` notation before even though I understand why it says it's not valid:

```
For instance:
    #11946=IfcStructuralSurfaceConnection('3ThFAZU718ageBY7oaRp4V',$,'Roof_Joists',$,$,#11951,#12125,$)
With inverse:
    ConnectsStructuralMembers : SET [1:-1] OF IfcRelConnectsStructuralMember FOR RelatedStructuralConnection
Value:
    ()
Not valid
```

**Comment by aothms** [comment]
Both of these appear to be valid error reports.

>     With inverse:
>         ToMaterialProfileSet : IfcMaterialProfileSet FOR MaterialProfiles
>     Value:
>         [
>           1. #171703=IfcMaterialProfileSet($,$,(#171705),$)
>           2. #171708=IfcMaterialProfileSet($,$,(#171705),$)
>         ]

`IfcMaterialProfileSet FOR MaterialProfiles` means min cardinality = max cardinality = 1

`[1:-1]` just means `[1:?]` (because we store it internally as an int). Should be more readable now.

`SET [1:-1] OF IfcRelConnectsStructuralMember FOR RelatedStructuralConnection` means min cardinality = 1 so `()` (empty) is not valid.

**Comment by Moult** [comment]
Ah thanks for the explanation! I've fixed an issue that probably led to the first scenario.

**Comment by Moult** [comment]
Came across this error when trying to validate https://github.com/IfcOpenShell/IfcOpenShell/issues/2915

```
Traceback (most recent call last):
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/bim/module/debug/operator.py", line 101, in execute
    ifcopenshell.validate.validate(IfcStore.get_file(), logger, express_rules=True)
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 374, in validate
    assert_valid(attr_type, val, schema, attr=attr)
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 203, in assert_valid
    invalid = len(val) < b1 or (b2 != -1 and len(val) > b2) or not all(assert_valid(ty, v, schema) for v in val)
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 203, in <genexpr>
    invalid = len(val) < b1 or (b2 != -1 and len(val) > b2) or not all(assert_valid(ty, v, schema) for v in val)
  File "/home/dion/.config/blender/3.4/scripts/addons/blenderbim/libs/site/packages/ifcopenshell/validate.py", line 210, in assert_valid
    raise ValidationError(f"With attribute:\n    {attr or attr_type}\nValue:\n    {val}\nNot valid\n", (attr or attr_type).name())
AttributeError: 'aggregation_type' object has no attribute 'name'
```

**Comment by aothms** [comment]
@Moult your issue should be resolved now.

@Andrej730 your issue was already addressed in https://github.com/IfcOpenShell/IfcOpenShell/commit/c71a5a4d650bb8b2072442aa42efb264c29ffd4c

**Comment by Andrej730** [comment]
Hmm, tried it with the latest build (https://github.com/IfcOpenBot/IfcOpenShell/commit/198fa67cc1afc466432a7ca73141a443de72ef1e#comments based on 198fa67) and issue is still present

**Comment by aothms** [comment]
@Andrej730 Strange.

I have the following:

```
$ cat indexed-poly-no-segments.ifc
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
FILE_NAME('','2023-04-13T10:36:54',(),(),'IfcOpenShell v0.7.0-198fa67cc','IfcOpenShell v0.7.0-198fa67cc','');
FILE_SCHEMA(('IFC4'));
ENDSEC;
DATA;
#1=IFCCARTESIANPOINTLIST2D(((0.,0.),(1.,0.)));
#2=IFCINDEXEDPOLYCURVE(#1,$,.F.);
ENDSEC;
END-ISO-10303-21;
```

    $ python -m ifcopenshell.validate --rules indexed-poly-no-segments.ifc

Does not report anything.

**Comment by Andrej730** [comment]
Figured it out - it was a problem on my end, issue is gone.

**Comment by cvillagrasa** [comment]
I'm getting a missing IfcLogical `SelfIntersect` for IfcIndexedPolyCurve in IFC4x3. Shouldn't it be [optional and IfcBoolean](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcIndexedPolyCurve.htm#8.9.3.36.3-Attributes)?

```python
2023-04-23:12:39:40,773 ERROR   [validate.py:377] For instance:
    #3009=IfcIndexedPolyCurve(#3008,(IfcLineIndex((1,2)),IfcLineIndex((2,3)),IfcLineIndex((3,4)),IfcLineIndex((4,1))),$)
                                                                                                                      ^ 
With attribute:
    <attribute SelfIntersect: <type IfcLogical: <logical>>>
Not optional
```

Thanks in advance,

**Comment by aothms** [comment]
@cvillagrasa sorry for the delay. This is an unfortunate confusing situation.

> IFC4X3 indeed has IfcIndexedPolyCurve.SelfIntersect as an IfcLogical. This is in line with all other SelfIntersect attributes (e.g IfcOffsetCurve2D), but not inline with the definition of IfcIndexedPolyCurve.SelfIntersect in schemas IFC4 and IFC4X3_TC1. This is indeed confusing. Always use IFC4X3_TC1 or later.

**Comment by cvillagrasa** [comment]
Mmm interesting! ok, noted. Don't even start apologizing about any delay, you creator of IfcOpenShell 😂🙌🏻

So then it's IFC4X3 being different than anything before and after it, on that SelfIntersect attribute.

I don't see vanilla IFC4X3 even listed on [the tehcnical specs](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/), only IFC4X3_TC1 and IFC4.3.1.0 in development.

I was using `ifcopenshell.api.run("project.create_file", version='IFC4X3')` and thought that was already creating a TC1. I see that it works if I pass a `version='IFC4X3_TC1'` instead, but then things like `ifcopenshell.util.pset.get_template(file.schema)` fail with KeyError.

Shouldn't the default 'IFC4X3' be TC1?

**Comment by cvillagrasa** [comment]
Kind of related maybe: I see this minibug on the main Readme:
![imagen](https://user-images.githubusercontent.com/57069798/235379499-86412055-0645-4ccc-b8a8-95211e5bc20a.png)

**Comment by aothms** [comment]
> I don't see vanilla IFC4X3 even listed on [the tehcnical specs](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/), only IFC4X3_TC1 and IFC4.3.1.0 in development.

> Shouldn't the default 'IFC4X3' be TC1?

That's a good point. TC1 is mostly a set of bugfixes, IFC4X3_ADD1 adds some new things. Maybe we should indeed help users with this, but I don't know what'd be the proper way to nudge people to the correct version without limiting functionality..

**Comment by cvillagrasa** [comment]
[Here](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/ifc-release-notes/) it's referenced as "IFC4X3_RC1". Since it's a deprecated version, does it make sense to call it with that release candidate suffix, and make  default "IFC4X3" whatever is the latest stable version (in this case: "IFC4X3" = "IFC4X3_TC1")?

**Comment by Moult** [comment]
The names given on the tech spec pages are not **schema identifiers**, they're just version names. I assume once ISO approval gets closer a schema identifier will be locked in.

**Comment by cvillagrasa** [comment]
But now the high level API works with deprecated IFC4.3.0.0, while it crashes with stable IFC4X3 TC1 under ISO voting.

I don't know, but if I'm understanding correctly the ifcparse folder, currently "IFC4X3" gets generated from IFC4x3_RC2.exp. For comparison, "IFC4" gets generated from IFC4.exp. The thing is that both official EXPRESS definitions for IFC4.0.0.0 and IFC4 ADD2 TC1 are called "IFC4.exp":

https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/EXPRESS/IFC4.exp
https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/EXPRESS/IFC4.exp

I would expect `ifcopenshell.file(schema="IFC4")` to produce the current ISO 16739-1:2018 version, instead of the deprecated IFC4.0.0.0 (which I hope it does). In fact, attempting something like `ifcopenshell.file(schema="IFC4_ADD2_TC1")` throws a `RuntimeError`.

But in IFC4X3, there isn't an ISO standard yet and thing are different. We need to explicitly indicate `schema="IFC4X3_TC1"` or otherwise, IFC4.3.0.0 rc2 is chosen.

Isn't it preferrable to make "IFC4X3" to point to TC1 at the moment (even before ISO voting, because there's no prior 4X3 non-deprecated version), and make it point to ADD1 whenever IFC4.3.1.0 becomes ISO in the future? Breaking changes due to this could be easily handled by freezing the IfcOpenShell version.

**Comment by aothms** [comment]
Just a quick comment. TC1 != RC1. Technical Corrigendum vs Release Candidate. The official schemas can be found here https://github.com/buildingSMART/IFC4.3-html/releases TC1 is sep-13 (iirc).

The schemas in ifcopenshell are generated from the exact schema identifiers in the schema.

But this is where things are a bit different from previous releases (IFC4). With IFC4 bSI decided never to change the schema identifiers when the various TCs and addenda came in. Which might introduce incompatibilities. Now we have a different situation that requires people to carefully choose a schema version (at least now, until we have final deliverable ratified by iso).

**Comment by Moult** [comment]
Closing as no new express bugs noticed for a while now.
