### ISSUE TITLE
ifcopenshell.validate to check if guids and other attributes are unique

### ISSUE THREAD

**Issue by Andrej730** [IfcOpenShell/IfcOpenShell#4499]
Noticed that running `ifcopenshell.validate.validate()` doesn't detect if IFC file has duplicated guids (IfcRoot.UR1 rule).

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/c9bc7104-fb43-4653-9684-bc1b4249d0e5)

```python
import ifcopenshell
import ifcopenshell.validate

def validate_ifc_file(ifc_file: ifcopenshell.file, use_json=False):

    if use_json:
        logger = ifcopenshell.validate.json_logger()
    else:
        import logging

        logger = logging.getLogger("validate")
        logger.setLevel(logging.DEBUG)

    ifcopenshell.validate.validate(ifc_file, logger, express_rules=True)
    if use_json:
        from pprint import pprint

        pprint(logger.statements)

ifc_file = ifcopenshell.file(schema="ifc4")
guid = "3pdqyORIn8KBHZAhhtJ72T"
ifc_file.createIfcWall(GlobalId=guid)
ifc_file.createIfcWall(GlobalId=guid)
validate_ifc_file(ifc_file)

```

I've added a fix in https://github.com/IfcOpenShell/IfcOpenShell/commit/bf9bddc867b5ad70a1da973998826ea0f6f2b1c0 checking it inside `validate()` but not sure if it's the best approach - maybe it should be handled as some file scope rule in generated https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/express/rules/IFC4.py based on `UNIQUE` keyword in .exp file.

Though `UNIQUE` occurrs only 3 times in .exp files entity definitions and guid seems to be the most imporant case with it, so maybe it's okay to just check it in `validate()` for now.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/22dfcdda-6549-4e33-89d4-5a25124dd1af)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/0ffdcd96-942e-4f8d-afa0-e06e92441b6f)

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/9417531/abc92c26-3433-42c6-b715-dcdecc274104)

**Comment by aothms** [comment]
Yes we have an issue for this in the validation service backlog, we'll likely get to it at some point. 

Unique lists also exist btw.

![Uploading afbeelding.png…]()

**Comment by BIMvoice** [comment]
Resolved on the current v0.8 line. The EXPRESS WHERE-rule validation now covers the uniqueness rules: validating a file with two IfcWall sharing a GlobalId (validate(..., express_rules=True)) reports one "IfcRoot.UR1" GlobalId-uniqueness violation, and a file with unique GlobalIds reports none (no false positive). Recommend closing as fixed.

**Comment by aothms** [comment]
The case of IfcGridAxis or a general validation of UNIQUE clauses in the schema is still not implemented. Only the most common cases. Keep open.

**Comment by BIMvoice** [comment]
You are right, my earlier note was premature. I opened #8517 which broadens this: a generic table-driven pass (validate_uniqueness_rules) that generalises the hard-coded IfcApplication check to every other entity-level UNIQUE clause in the supported schemas (IfcPropertyEnumeration.UR1 in IFC4+, plus the IFC2X3 set: IfcActionRequest, IfcCostSchedule, the material-properties family, IfcOrderAction, IfcPermit, IfcProjectOrder). IfcRoot.UR1 and IfcApplication keep their dedicated paths to avoid double-reporting.

One correction while looking into this: IfcGridAxis has no entity-level UNIQUE clause. Its constraints are WHERE rules (WR1/WR2), and the uniqueness on grid axes is a LIST OF UNIQUE aggregate (a different construct), so it is not covered by this UR pass.

I kept it as Refs rather than Fixes and left the issue open: a fully generic pass still needs the UNIQUE clauses exposed at runtime. They are dropped before runtime today (the compiled schema wrapper has no UNIQUE accessor, and express rule_compiler only emits WHERE/DERIVE, not unique_clause, even though the parser already captures it in nodes.entity_definition.unique). So the two routes to full generality are: surface UNIQUE on the C++ schema/entity wrapper, or have rule_compiler emit the parsed unique clauses (noting they are cross-instance, so they do not fit the per-instance rule_executor). Happy to take either on if you have a preference.
