### ISSUE TITLE
Bugs in light simulation

### ISSUE THREAD

**Issue by manuvarkey** [IfcOpenShell/IfcOpenShell#5033]
I was testing out the light simulation feature newly merged in BlenderBIM. Following points require correction.

1. When selecting a JSON path error is shown in linux showing both source and destination file paths used by `shutil.copy` as same. Source of the error seems to be the below line which only works on windows.
https://github.com/IfcOpenShell/IfcOpenShell/blob/9bf68db0806e451ae927ccb8a64a6c8ecbc13622/src/blenderbim/blenderbim/bim/module/light/operator.py#L156
On Linux this requires modification to `json_dest_path = os.path.join(blend_file_dir, json_file_path.split("/")[-1])` to work correctly. Probably it may be better to use a platform agnostic method to achieve the logic.

2. When path to the project directory contains white spaces, following error is reported when running 'Radiance Render'. It may be needed to escape the white spaces in the file paths before sub-process is called.

![Screenshot from 2024-07-18 11-10-35](https://github.com/user-attachments/assets/210b6bab-407a-4e81-a9b6-32ec73d532d5)

Further in the interface I find the following observations for improvement.

![Screenshot from 2024-07-18 11-14-43](https://github.com/user-attachments/assets/532c1c6c-6d7d-4e90-b3d5-8f5f721d8dfd)

1. I would question why the `IFC filename` field is required at all since the information is available for an active project. 
2. Also the `JSON file` field cannot be understood by the lay user. It should be possible to render out the project even if this field is missing by using the default parameters. Also better documentation is required in the tool tip explaining what is the JSON file.
3. I would rename the `Export to OBJ` button to `Export Geometry for Simulation` and disable the `Radiance Render` button until geometry is exported.

Platform: `Ubuntu 22.04`
Blender: `4.2`
BlenderBIM: `0.7.10.240714`

@chiragsingh1711

**Comment by chiragsingh1711** [comment]
Hey Manu,
thank you so much for pointing out these corrections.
In the next push, I'll make sure all these corrections are made and will
surely improve the interface as well.
Really appreciate your input.

**Comment by chiragsingh1711** [comment]
Done @manuvarkey , I have pushed the changes https://github.com/IfcOpenShell/IfcOpenShell/commit/e88abd881dd9e582845d016f87e5faec1c4c0678

**Comment by chiragsingh1711** [comment]
Please review and let me know if you find more bugs. @manuvarkey

**Comment by manuvarkey** [comment]
Hi @chiragsingh1711 Great work! 

**1. Regarding the error with white spaces in filepath**

Issue still persists. But the issue seems to be related to upstream for the major part. I have raised a bug report upstream https://github.com/LBNL-ETA/pyradiance/issues/38. 

I had to make the following modifications in the `pyradiance` package to  work around the issue.
https://github.com/manuvarkey/pyradiance/pull/1.

The following line in `module/light/operator.py` requires modification to escape white spaces in `rtm_file_path`.
 https://github.com/IfcOpenShell/IfcOpenShell/blob/e88abd881dd9e582845d016f87e5faec1c4c0678/src/blenderbim/blenderbim/bim/module/light/operator.py#L181

`file.write('void mesh model\n1 "' + rtm_file_path + '"\n0\n0\n')`

**2. Error with permissions for executables inside pyradiance**

Following error is shown.

![Screenshot from 2024-07-21 12-53-44](https://github.com/user-attachments/assets/6b00f53d-ea19-4835-950a-491f705b4e8e)

Error is not shown after setting executable permission for all files inside `pyradiance/bin`

**Comment by manuvarkey** [comment]
Just random thoughts

1. It is seen that all styles are now set to white. Any plans on using the material style data in the IFC file for render ?
2. Does IFC & BlenderBIM supports defining `IES` files for `IfcLightFixture`. Is it possible to use this data for rendering ?
3. Is it possible to output render results to `BMP`/`JPG`/`PNG` ?
4. Is it possible to define light calculation surfaces in BlenderBIM and use Radiance to calculate results for these surfaces ?

**Comment by Moult** [comment]
1. Specifically lighting styles, not shading or rendering styles, yes. On the roadmap for gsoc.
2. Yes planned, hopefully in the gsoc roadmap
3. Good idea, should be easy to add
4. Not currently in scope for gsoc. We're actually doing something a bit different here - I'm focusing on luminance renders (see my blog post on photorealistic rendering with radiance - so priorities include object proxies, textures, and large model obj splitting)

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by manuvarkey** [comment]
**1. Regarding the error with white spaces in filepath**

Now upstream bug report https://github.com/LBNL-ETA/pyradiance/issues/38 has been resolved and new release of `pyradiance` has been released (https://github.com/LBNL-ETA/pyradiance/releases/tag/v0.4.2).

Updating pyradiance to the latest release and modifying 
https://github.com/IfcOpenShell/IfcOpenShell/blob/e88abd881dd9e582845d016f87e5faec1c4c0678/src/blenderbim/blenderbim/bim/module/light/operator.py#L181
to `file.write('void mesh model\n1 "' + rtm_file_path + '"\n0\n0\n')` should resolve this issue.

**Comment by chiragsingh1711** [comment]
@manuvarkey 

Radiance Progress Update:

Created a "Upload JSON" toggle.
When True, the user can select a pre existing JSON file.
When False, all the material styles will be listed and the user can manually build the json inside the UI.
(Yes, materials are working now 🥳)

Fixed the white space issue with the help of Manu who reported the bug to pyradiance and got the issue fixed. Thanks to him !

Enable the user to choose the output file name and extension.

Disabled Render button while the Geometry is being exported.

Tasks Pending:

Choosing some materials from https://spectraldb.com/ and let user choose materials from that list.
Implementing gensky

https://github.com/IfcOpenShell/IfcOpenShell/commit/0dde4102bc438168fd86c8b1e74c275a5d964aca

**Comment by manuvarkey** [comment]
The error with non setting of executable flag for radiance binaries is still there. The following error is shown due to this. Error goes away once the executable settings are applied manually.
```
Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/anci.py", line 22, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/cv.py", line 92, in obj2mesh
    return sp.run(cmd, check=True, input=stdin, stdout=sp.PIPE).stdout
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/blender/5088/4.2/python/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/blender/5088/4.2/python/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/snap/blender/5088/4.2/python/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/bin/obj2mesh'
```

I think the issue may be due to the way blender installs addons. The pyradiance wheels archive has proper executable flags set for binaries. I could find the following on stack exchange which deals with the same error.
https://blender.stackexchange.com/questions/310144/mac-executable-binary-within-addon-zip-loses-execute-permission-when-addon-zip

Following solution needs to be reviewed for addressing the error.
https://blender.stackexchange.com/a/310778

**Comment by manuvarkey** [comment]
Some comments for brainstorming.
1. It may be better to add material mappings using something inside a [UIList](https://docs.blender.org/api/current/bpy.types.UIList.html) to be consistent with other parts of the addon.
Something like this
![Screenshot from 2024-07-26 11-06-43](https://github.com/user-attachments/assets/6253a272-a7fa-4aa2-88d8-dbb7295bca18)
https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/blenderbim/bim/module/profile/ui.py#L115-L123
2. Running of OBJ export and final render in separate thread so as not to lock blender interface.
3. Possibility of running the render on section views especially drawing views. Currently could not test this aspect properly as the drawings panel is throwing a bunch of errors. Currently activating a drawing view and running render throws the following error.
```
Python: Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/anci.py", line 22, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/util.py", line 819, in rtpict
    proc = sp.run(cmd, check=True, stdout=sp.PIPE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/blender/5088/4.2/python/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/bin/rtpict', '-vtv', '-vp', '12.5', '5.039999961853027', '1.600000023841858', '-vd', '0.0', '0.0', '-1.0', '-vu', '0', '0', '1', '-vh', '45', '-vv', '45', '-vo', '0', '-va', '0', '-vs', '0', '-vl', '0', '-n', '1', '-x', '1920', '-y', '1080', '-dt', '0.05', '-ds', '0.2', '-dr', '3', '-ad', '4096', '-as', '128', '-aa', '0.075', '-ar', '128', '-lr', '12', '-lw', '5e-06', '-ab', '1', '-af', 'ascene.amb', '-as', '2048', '-av', '0.01', '0.01', '0.01', '-dc', '0.75', '-dp', '4096', '-ms', '0.081', '-ss', '16.0', '-st', '0.01', 'ascene.oct']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eee/.config/blender/4.2/extensions/.local/lib/python3.11/site-packages/pyradiance/anci.py", line 25, in wrapper
    raise RuntimeError(
RuntimeError: An error occurred with exit code 1: 

```

May not be in the scope of this project. But following extended features may prove to be pretty useful useful for engineering applications (lighting, daylight analysis).
1. Defining light calculation surfaces to calculate lux level, uniformity, glare and daylight factor.
2. Doing false colour/ contour/ value map of calculation surfaces/ scene.

**Comment by manuvarkey** [comment]
Can confirm that the Executable permission error is now resolved. 

Any reason why HDR path is hard coded to `render123` ?
https://github.com/IfcOpenShell/IfcOpenShell/blob/90c6218210fd57cc910d6fff7a13a963b8cb4ddf/src/blenderbim/blenderbim/bim/module/light/operator.py#L337

**Comment by chiragsingh1711** [comment]
@manuvarkey Yes Manu, that hardcode was done for testing. I'll correct that in the next commit.
Plus in the next commit I would have implemented the UI List as you mentioned. 
And I am working on your second point: "Running of OBJ export and final render in separate thread so as not to lock blender interface."

**Comment by manuvarkey** [comment]
It seems there is an issue with timezone and true north. On account of this, the shadows displayed in blender viewport is differing from the rendered image (Viewport render seems to be correct).

See following viewport render.
![With original settings](https://github.com/user-attachments/assets/5091a54e-f69b-4ca5-9b29-2b0fdbf6e04e)

Corresponding radiance render.
![render](https://github.com/user-attachments/assets/09bf8a91-d9ea-4de3-aef5-15768098f166)

Modifying viewport settings so as to match with radiance render (by removing true north and setting local time as corresponding UTC time used for render).
![correction to match rendering](https://github.com/user-attachments/assets/f25b3af9-523f-41c7-a81b-dbf112e54b8c)

**Comment by manuvarkey** [comment]
Some observations:
1. There is no order of entries in SpectralDB category and sub category. It may be better to sort these alphabetically for easier selection. Some kind of search will also be good.
2. Refreshing materials clears all material mappings. It will be better to retain mappings while refreshing.

Also how is it possible to assign a radiance material map for glass surfaces ? I couldn't see any option in SpectralDB list.

**Comment by manuvarkey** [comment]
https://github.com/IfcOpenShell/IfcOpenShell/blob/96fdced471e1a148ee97549404044abf1e10f291/src/blenderbim/blenderbim/bim/module/light/operator.py#L510-L517

Why IfcSurfaceStyleShading elements are discarded ? I do not have a full understanding of the style classes. But some of my styles are not showing up in the list of materials. I am thinking this may be the reason.

**Comment by Moult** [comment]
This is really great feedback, Chirag and I had a meeting yesterday going through this and we identified exactly the same issues. I made a list and posted it in the chat:

<moult:matrix.org> chiragsingh1711:matrix.org: 1) fix solar bug, use azi/alt instead of dt 2) allow specifying camera, use PointerProperty to bpy.types.Object 3) some basic print statements in console to know what's happening for long running process, 4) show active object style 5) show style colour in list 6) from bonsai.bim.helper import prop_with_search to search styles 7) save as json 8) split obj generation separate from other material rad / rtm generation 9) fix camera resolution 10) glass presets

chiragsingh1711:matrix.org: single pane clear glazing example https://dpaste.com/6F9WM5FSD

<moult:matrix.org> chiragsingh1711:matrix.org: also nproc for multiprocessing during rendering

**Comment by manuvarkey** [comment]
On Ubuntu 24.04, render fails (`ra_tiff` conversion stage) due to shared dependency error. Have raised a bug report.

https://github.com/LBNL-ETA/pyradiance/issues/40

**Comment by manuvarkey** [comment]
`pyradiance` while running the render, creates the `ascene.oct`, `ascenemat.oct` and `ascene.amb` in the process working directory. This leads to creation of these files under Home folder on Linux. Not sure about other OS. 

There seems to be no option in `pyradiance` to set a working director while calling `pr.render`. Filenames are set at working directory using `scene.sid` variable as follows.

https://github.com/LBNL-ETA/pyradiance/blob/f3b80e8ee4e7ed59b7e21ec2228da9918918c36a/pyradiance/util.py#L679
https://github.com/LBNL-ETA/pyradiance/blob/f3b80e8ee4e7ed59b7e21ec2228da9918918c36a/pyradiance/util.py#L716

It is possible to set working directory in python while calling the process as follows which seems to work ok on Linux.

```
        cwd_saved = os.getcwd()
        os.chdir(output_dir)
        image = pr.render(
            scene,
            ambbounce=1,
            resolution=(resolution_x, resolution_y),
            quality=quality,
            detail=detail,
            variability=variability,
            nproc=multiprocessing.cpu_count(),
        )
        os.chdir(cwd_saved)
```

I am not sure if this is the right approach.

**Comment by Moult** [comment]
@chiragsingh1711 hey Chirag! Any thoughts on getting some closure on this? I also believe you still have a PR which needs merging.

**Comment by chiragsingh1711** [comment]
Hi @Moult ! Yes I still had a PR pending. My whole day went in fixing an error I was getting while using the functions of pyradiance. When I was calling those functions normally through Command prompt, they were working fine but when I called them through Blender's env, it threw an error. After reinstalling everything and still no fix. At last I figured out it was that my Visual C++ Redistributable had multiple installations of different versions. Uninstalling all versions and installing the latest one worked for me.
And thanks @manuvarkey for pointing out about generation of ascene.oct, ascenemat.oct and ascene.amb.

Creating a PR from light/newUI

**Comment by falken10vdl** [comment]
@chiragsingh1711 can you update us on this please? Has a PR been done?
Thanks!

**Comment by chiragsingh1711** [comment]
Hiii @falken10vdl !
Yess I remember my PR was merged. 
I contributed in this feature last year, so I am totally offtrack what new things came in while transitioning into Bonsai. I'll setup the dev env again and have a check asap where there is an error

**Comment by falken10vdl** [comment]
Excelent @chiragsingh1711 . Thanks for your help!
