### ISSUE TITLE
Missing or incorrect alignment

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#5072]
I've got two (private) files attached exported from 12D (a very popular civil software here in Australia).

The first, P*.ifc is exported with a checkbox called "Export 3d alignment" disabled. I notice it contains no shape representations at all, so naturally if I try to view it I see nothing. However it still has the DesignParameters attribute filled out. What should viewers do in this case? Should it actually show nothing? Can IfcOpenShell still calculate the representation from these design parameters?

The second is with the checkbox "Export 3d alignment" enabled. It's _almost_ correct. I've attached screenshots (sent privately) of what it should look like in 12D. You'll notice two alignments on either side look truncated. That's because the horizontal alignment is longer than the vertical. So I guess this is somewhat undefined, but I guess the question is:

 1. Should it continue the horizontal but keep the elevation at 0 when vertical is undefined? i.e. step up and down when where is no vertical data
 2. Or should it continue flat at the last known elevation?
 3. Or is the current behaviour of "missing" intentional? The guy I spoke to who helped provide this issue explained that he still wanted to know the horizontal, even when there is no vertical data.
 4. Regardless of whether it is zeroed out, continued flat, or missing, you'll notice the start point (orange dot) is not truncated, but it only truncates at the very end (presumably when it runs out of vertical alignment). However what should actually happen (and other software from Bentley will do this apparently) it should truncate both at the beginning and the end (at a total guess, is this based on the `StartDistAlong` attribute of `IfcAlignmentVerticalSegment`?)

This diagram attempts to explain that last point:

![2024-07-24-183202_525x751_scrot](https://github.com/user-attachments/assets/e2f3643c-edb9-4ec8-835b-8866bd84bf7f)

**Comment by RickBrice** [comment]
> Can IfcOpenShell still calculate the representation from these design parameters?

On the C++ side there is some code in the IfcParse library that can generate IfcCurveSegment from the DesignParameters. From there I guess the IfcCurveSegment could be mapped to geometry. The mapping of business logic to geometry is mostly complete for horizontal and vertical, no implementation for cant just yet. See https://github.com/IfcOpenShell/IfcOpenShell/blob/8b29e50f11da2730a19d21327c22a257d0434c9e/src/ifcparse/IfcAlignmentHelper.h and https://github.com/IfcOpenShell/IfcOpenShell/blob/8b29e50f11da2730a19d21327c22a257d0434c9e/src/ifcparse/IfcAlignmentHelper.cpp. Not sure how this maps into the python/Blender universe.

> Or is the current behaviour of "missing" intentional? The guy I spoke to who helped provide this issue explained that he still wanted to know the horizontal, even when there is no vertical data.

The behavior is intentionally on the advice of the bSI-IF. You should still be able to get the full horizontal without the vertical from the IfcCompositeCurve and a "FootPrint" representation (is that the correct terminology?).

> you'll notice the start point (orange dot) is not truncated, but it only truncates at the very end

There is no truncation at the start because the vertical always begins at the start of the horizontal. IfcGradientCurve.BaseCurve=IfcCompositeCurve is the horizontal. It is made up of segments defined by length. IfcGradientCurve.Segments is the vertical. It is also made up of segments defined by length. There isn't a way to apply an offset between the horizontal and vertical list of segments so both sequences of segments start at the same place (unless I'm missing a fundamental concept).

**Comment by Moult** [comment]
> There is no truncation at the start because the vertical always begins at the start of the horizontal. IfcGradientCurve.BaseCurve=IfcCompositeCurve is the horizontal. It is made up of segments defined by length. IfcGradientCurve.Segments is the vertical. It is also made up of segments defined by length. There isn't a way to apply an offset between the horizontal and vertical list of segments so both sequences of segments start at the same place (unless I'm missing a fundamental concept).

This is the bit I'm confused about. Apparently according to the author, Bentley manages to parse the IFC and see the truncation happen at two points (somewhere along the start, and somewhere along the end) in accordance with what the original software (12D) has intended.

**Comment by civilx64** [comment]
> You should still be able to get the full horizontal without the vertical from the IfcCompositeCurve and a "FootPrint" representation (is that the correct terminology?).

Yes, this is the exact correct terminology. bBIM should always display the full limits of the horizontal IfcCompositeCurve in the XY plane, along with whatever sub-portion of IfcCompositeCurve has vertical and (optionally) cant applied.

> There isn't a way to apply an offset between the horizontal and vertical list of segments so both sequences of segments start at the same place (unless I'm missing a fundamental concept).

There has to be a way to do this because this situation (portions of horizontal at beginning and end with no corresponding vertical definition) are very common - in fact in my experience it's much more rare to have a situation where the vertical covers the full limit of the horizontal.

**Comment by Moult** [comment]
> My understanding is that the placement of the segments of IfcGradientCurve determine where the vertical starts relative to the horizontal.

Yes this seems to make sense and I agree with your email message too @civilx64 :

> 
> Apologies, I know I'm jumping between the GH issue and this thread.  Rick
>    - look at the placement of the first segment in the IfcGradientCurve
>    (#493) and compare to its corresponding business logic segment (#317).  In
>    #317 the StartDistAlong is 140.0659 m and StartElevation is 222.904.  This
>    corresponds to the placement of #493 where in the 2D vertical space of
>    (distance along, elevation) the first segment is placed at (140.0659,
>    222.904).

Here's what you described shown graphically in Blender:

![2024-07-25-105854_692x502_scrot](https://github.com/user-attachments/assets/4993bd42-d28b-4ce6-a5cc-4ce046f4a150)

**Comment by Moult** [comment]
Also, given that the horizontal alignment is pure XY, I'd prefer not to display it (or the vertical) by default in Blender as it might confuse users into thinking it is truly a 3D object whereas it is purely a 2D definition. I'd prefer for users to explicitly enable a mode which toggles the display of horizontal / verticals for selected alignments, which are then overlayed in a special way that truly reflects its 2D nature, and offers little labels of segments, with editing options, maybe annotating curve types, etc. So ideally there should still be a good initial experience somehow with just the 3D alignment that indicates that there is extra data in the horizontal where data in the vertical is missing.

**Comment by RickBrice** [comment]
Well dang it. None of the examples had this case and it never crossed my mind. You learn something new every day. This should be easy to accommodate. Give me a couple days and I’ll get it fixed up. 

Should we consider having some options in "Settings" that gives some choices for truncated curves? There are several scenarios to think through. What if vertical is longer than horizontal (not practical, but possible)? Should elevation be 0.0? Should it be the elevation at the end of the last segment? Should we project a gradient at the slope and direction of the last segment? Or first segment if the start points are offset? Could get complicated - maybe a bad idea.

**Comment by civilx64** [comment]
> What if vertical is longer than horizontal (not practical, but possible)?

This could be considered a validation error, or possibly a warning.  For IFCOS parsing we should hold the limits of horizontal and calculate the elevation of the vertical at the highest DistAlong on the horizontal.  But yes, it does get a bit tricky if the vertical is ending on a vertical curve as there may be a need to define a vertical curve length that ends up beyond the limits of horizontal but the vertical profile ends at a point within that curve.  I know I have done this in practice at least once, for smoothing at an intersection IIRC.

**Comment by civilx64** [comment]
> Also, given that the horizontal alignment is pure XY, I'd prefer not to display it (or the vertical) by default in Blender as it might confuse users into thinking it is truly a 3D object whereas it is purely a 2D definition.

I'm sure this falls into the larger overall discussion regarding infrastructure UI but the user expectation is to see the entire limit of all horizontal alignments with the understanding that they are 2D only.  Particularly when the horizontal alignment is annotated with markers for stations (referents) and critical points such as POB / POE, PC/PI/PT, TS/SC/CS/ST.

**Comment by RickBrice** [comment]
@civilx64 @Moult What is the prevailing thinking on IfcSegmentedReferenceCurve that have start/end points that are not aligned with the IfcGradientCurve or IfcCompositeCurve?

I could constrain IfcSegmentReferenceCurve to the smallest range where all three curve types are defined. Alternatively, I could assume no superelevation transition or cant tilt in regions of the IfcGradientCurve where IfcSegmentedReferenceCurve is not defined.

**Comment by civilx64** [comment]
> I could constrain IfcSegmentReferenceCurve to the smallest range where all three curve types are defined.

This is the correct approach.  I'd recommend a similar approach for IfcGradientCurve where the 3D curve is defined over the shortest common range of the two curve types.  Providing an elevation of 0.0 in the Gradient Curve outside the limits it is actually defined is not technically correct and could be a very small "jump" for a project near sea level, say in Boston, MA.

**Comment by RickBrice** [comment]
That’s my plan to IfcGradientCurve. Out here by the west coast mountain ranges, the “jump” from 0.0 would not be small. 

I’ll use the smallest range common to all curves involved and emit an error if there are no non-zero overlapping ranges. 

Seems like we could get away with zero cant in undefined areas of the segmented reference curves since it is essentially a modifier on gradient curve, but it doesn’t “feel” right to do so. We can let the rail domain experts tell us otherwise if they don’t like the smallest overlapping range approach.

**Comment by aothms** [comment]
> Seems like we could get away with zero cant in undefined areas of the segmented reference curves since it is essentially a modifier on gradient curve

I think it's the same though. Both add dimensionality. Maybe because the 2d -> 3d is more visually obvious when visualized as a curve alone, but I guess when driving a train along the curve, a sudden jump to zero for elevation is equally catastrophic as a sudden jump to zero for tilt.

I think the only correct solution is to only show the intersection over the curve domains, but also have UX for showing the dimensions in isolation.

10 years ago I used the Blender Timeline to render 2d (time based) waveforms. The UI/Image editor would be more interactive though. Maybe there is something we can use for 2D ui? https://www.blendernation.com/2014/09/11/openpstd-acoustic-simulator/#prettyPhoto

**Comment by Moult** [comment]
If ifcopenshell provides a way to distinguish edges for which data is missing, we can visualize it in Blender with a different color (e.g. blue where data is complete and red where there is extrapolated or zero'd data)

Dion Moult

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by civilx64** [comment]
> 10 years ago I used the Blender Timeline to render 2d (time based) waveforms. The UI/Image editor would be more interactive though. Maybe there is something we can use for 2D ui? https://www.blendernation.com/2014/09/11/openpstd-acoustic-simulator/#prettyPhoto

Nice work on the audio analysis!  I like the idea of using the timeline to show vertical and cant as two separate tracks. That would also allow us to animate some geometry that moves along the alignment as you click around in the timeline. In other words selecting a point on the timeline (a station on an alignment) moves a transverse cylinder to that 3D point and rotation on the alignment. This would also allow for plotting additional vertical elements such as ditch profiles or edges of pavements. And in addition to moving the cylinder around for tracking purposes you could also update the plan view camera so that it is focused on (and potentially rotated to) the alignment at that station.  Then you could have a 2nd view with 3D isometric and a third view of UV/Image editing that corresponds to a cross section at the current station on the timeliner. 

Perhaps this concept falls apart when you go to do 4D construction simulation for an infra project? 🤔

**Comment by RickBrice** [comment]
I’m getting close to having this resolved. I’m trying to plot values using python but, as you know, I’m no pro at that. So, a couple set of questions regarding python and bindings. 

C++ std::pair mapping to python. I want piecewise_function to have a function called “range” that returns the applicable domain of the function. Function signature is  `std::pair<double,double> range() const` and it returns the first and last values that can be used in `pwf->evaluate(u)`

Does this map to python ok?
On the python side, how do you get the two values returned in the pair?
Is `domain` a better function name than `range`?

I have an example using the pythons wrapper to get a pwf from an instance of IfcGradientCurve. I call pwf->evaluate2() and get a std::pair containing a std::vector<double> of “distance along” values and the “loop” object. How do I loop over the “loop” and plot x,y and “distance along, z”?

**Comment by RickBrice** [comment]
Domain is the correct name

Domain: The set of all possible input values (usually represented by x) for which the function is defined.
Range: The set of all possible output values (usually represented by y) that the function can produce

**Comment by aothms** [comment]
> Does this map to python ok?

With SWIG templated STL things don't work out of the box. Not sure if it has something built in for std::pair, but the following lines should work (for example add to typemaps_out.i).

```
%typemap(out) std::pair<double, double> {
    $result = PyTuple_New(2);
    PyTuple_SetItem($result, 0, $1.first);
    PyTuple_SetItem($result, 1, $1.second);
}
```

But maybe while we're experimenting it's better not to wrap things in pairs, because it probably requires a typemap for everything. Maybe in this stage it's better to just duplicate to two functions. std::vector<double> and loop::ptr have their respective typemaps, but it's a bit ugly triggering them from another typemap for the pair.

> How do I loop over the “loop”

Does this work:

```
[edge.start.coords for edge in loop.children]
```

**Comment by RickBrice** [comment]
Fixed per https://github.com/IfcOpenShell/IfcOpenShell/commit/60b007d28a40150f907a73c6bcbcb21a20db501a

Notebook is attached. I refactored code as suggested. It's now really easy to get a vector of "distance along" from the piecewise_function.

Plot shows the full IfcCompositeCurve taken by itself with the truncated IfcCompositeCurve as the BaseCurve of IfcGradientCurve. Also shows vertical starts at non-zero location when start of gradient is offset from start of composite curve.

Juypter notebook to create the plots is attached.

![image](https://github.com/user-attachments/assets/2c562ae9-b1ee-4b20-9adc-f392f6df39df)

[GradientCurvePlot.ipynb.txt](https://github.com/user-attachments/files/16416433/GradientCurvePlot.ipynb.txt)

**Comment by aothms** [comment]
Super cool!

Maybe for @Moult and others interacting with the data simply through create_shape(), this still isn't the complete answer.

But I would also propose that rather than knowing of this potential issue of non-complete curve domains and wait for implementations to diverge, we better act as soon as possible to once again bring this up in IF and enforce this as some sort of rule or best practice.
