### ISSUE TITLE
Error building IfcOpenShell

### ISSUE THREAD

**Issue by e3dEF** [IfcOpenShell/IfcOpenShell#517]
Hello,

I face 19 warnings and 1 error, when building with the following cmd tool chain on 

- Win10, 64bit
- IfcOpenShell Branch 0.6
- VisualStudio 2017 (+ C++Toolchain), 64bit prompt
- Python 3.5 (64bit) - already installed

using
> cd IfcOpenShell\win
> build-deps.cmd
> run-cmake.bat
> install-ifcopenshell.bat

Until the run cmake, everything is fine. When executing the install bat from the visual studio command line, there is the following message after a few minutes:
```
Fehler beim Buildvorgang.

       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x86\INSTALL.vcxproj" (Standardziel) (1) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x86\ALL_BUILD.vcxproj" (Standardziel) (3) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x86\ifcwrap\_ifcopenshell_wrapper.vcxproj" (Standardziel)
        (6) ->
       (ClCompile Ziel) ->
         E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x86\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcPyth
       onPYTHON_wrap.cxx(202): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "Python.h": No such file
       or directory [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x86\ifcwrap\_ifcopenshell_wrapper.vcxproj]

    0 Warnung(en)
    1 Fehler
```
What could help in that case?

**Comment by Stinkfist0** [comment]
DId you install Python by yourself or did it install it via the build script? See https://github.com/IfcOpenShell/IfcOpenShell/tree/master/win#using-an-already-existing-python-installation

**Comment by e3dEF** [comment]
Hi,

thanks for your reply:
I now get another error, not related to Python


  ```
     "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\INSTALL.vcxproj" (Standardziel) (1) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ALL_BUILD.vcxproj" (Standardziel) (3) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj" (Standardzi
       el) (16) ->
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcparse\../ifcparse/IfcEntityInstanceData.h(80): warning C426
       7: "return": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcO
       penShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcparse\../ifcparse/IfcSpfHeader.h(54): warning C4267: "retur
       n": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcOpenShell-
       0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
         E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcP
       ythonPYTHON_wrap.cxx(4252): warning C4267: "return": Konvertierung von "size_t" nach "int", Datenverlust mögl
       ich [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
         E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcP
       ythonPYTHON_wrap.cxx(4569): warning C4267: "Argument": Konvertierung von "size_t" nach "int", Datenverlust mö
       glich [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
         E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcP
       ythonPYTHON_wrap.cxx(4583): warning C4267: "Argument": Konvertierung von "size_t" nach "unsigned int", Datenv
       erlust möglich [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxpr
       oj]
         E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcP
       ythonPYTHON_wrap.cxx(4595): warning C4267: "Argument": Konvertierung von "size_t" nach "unsigned int", Datenv
       erlust möglich [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxpr
       oj]
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcgeom\../ifcgeom/IfcGeomElement.h(105): warning C4267: "Argu
       ment": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcOpenShe
       ll-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcgeom\../ifcgeom/IfcGeomElement.h(106): warning C4267: "Argu
       ment": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcOpenShe
       ll-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]


       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\INSTALL.vcxproj" (Standardziel) (1) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ALL_BUILD.vcxproj" (Standardziel) (3) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\examples\IfcAdvancedHouse.vcxproj" (Standardziel)
       (4) ->
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcparse\../ifcparse/IfcEntityInstanceData.h(80): warning C426
       7: "return": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcO
       penShell-0.6.0\build-vs2017-x64\examples\IfcAdvancedHouse.vcxproj]
         e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcparse\../ifcparse/IfcSpfHeader.h(54): warning C4267: "retur
       n": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcOpenShell-
       0.6.0\build-vs2017-x64\examples\IfcAdvancedHouse.vcxproj]


e:\daten\ifcopenshell\ifcopenshell-0.6.0\src\ifcparse\../ifcparse/IfcSpfHeader.h(54): warning C4267: "retur
       n": Konvertierung von "size_t" nach "unsigned int", Datenverlust möglich [E:\Daten\IfcOpenShell\IfcOpenShell-
       0.6.0\build-vs2017-x64\examples\IfcAdvancedHouse.vcxproj]


       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\INSTALL.vcxproj" (Standardziel) (1) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ALL_BUILD.vcxproj" (Standardziel) (3) ->
       "E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj" (Standardzi
       el) (16) ->
       (ClCompile Ziel) ->
         E:\Programme\Visual Studio 2017\VC\Tools\MSVC\14.16.27023\include\algorithm(1443): error C2664: "const std:
       :string &(const IfcParse::declaration *)" : Konvertierung von Argument 1 von "const std::pair<const _Kty,_Ty>
       " in "const IfcParse::declaration *" nicht möglich [E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\build-vs2017-x64
       \ifcwrap\_ifcopenshell_wrapper.vcxproj]

    130 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:06:06.57

x64 RelWithDebInfo IfcOpenShell installation failed
```

Thank you for your help

**Comment by Stinkfist0** [comment]
Hmm, perhaps the same issue as in here: https://github.com/IfcOpenShell/IfcOpenShell/issues/512

**Comment by e3dEF** [comment]
Maybe I forgot some step? This was my chain:

- set IFCOS_INSTALL_PYTHON=FALSE in build-deps.com
- .\buid-deps.cmd
- edit BuildDepsCache-x64
GEN_SHORTHAND=vs2017-x64
OCC_INCLUDE_DIR=E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\deps-vs2017-x64-installed\opencascade-7.3.0\inc
OCC_LIBRARY_DIR=E:\Daten\IfcOpenShell\IfcOpenShell-0.6.0\deps-vs2017-x64-installed\opencascade-7.3.0\win64\lib
PY_VER_MAJOR_MINOR=35
PYTHONHOME=E:\Programme\Miniconda3_4.2.12_Py3.5
- .\run-cmake.bat
- .\install-ifcopenshell.bat

Is there another way, that I could try?
Thank you for your help and kind regards!

**Comment by e3dEF** [comment]
Those are the results using Visual Studio instead of the .bat:
![grafik](https://user-images.githubusercontent.com/41104642/49732296-68417800-fc7e-11e8-8cc5-29b6f8925314.png)

![grafik](https://user-images.githubusercontent.com/41104642/49732338-9030db80-fc7e-11e8-9a86-28ba33a455e0.png)


![grafik](https://user-images.githubusercontent.com/41104642/49732260-52cc4e00-fc7e-11e8-8bc4-34965e0d9c3c.png)

**Comment by aothms** [comment]
Should be fixed now, thanks for reporting.

**Comment by ricottatiago** [comment]
I am trying to install ifcopenshell and getting almost the same error from here, but even if I followed the steps (pre-instalation of python) I still cannot pass the following message:

> C:\build\IfcOpenShell\win>install-ifcopenshell.bat
> 
> Generator not passed, but GEN_SHORTHAND=vs2019-x64 read from BuildDepsCache
> 
> GENERATOR:           ["Visual Studio 16 2019"]
> VS_VER:              [2019]
> VS_PLATFORM:         [x64]
> VS_TOOLSET:          []
> VC_VER:              [14.2]
> ARCH_BITS:           [64]
> TARGET_ARCH:         [x64]
> BOOST_BOOTSTRAP_VER: [vc142]
> BOOST_TOOLSET:       [msvc-14.2]
> BOOST_WIN_API:       []
> build-type-cfg.cmd: Warning: BUILD_CFG not specified - using the default RelWithDebInfo
> 
> * IFCOS_NUM_BUILD_PROCS = 12
> 
> Installing x64 RelWithDebInfo IfcOpenShell
>   IfcParse.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcParse.lib
>   libsvgfill.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\svgfill\RelWithDebInfo\libsvgfill.lib
>   IfcGeom_ifc2x3.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc2x3.lib
>   IfcGeom_ifc4x1.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x1.lib
>   IfcGeom_ifc4x3_rc1.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x3_rc1.lib
>   IfcGeom_ifc4x3_rc2.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x3_rc2.lib
>   IfcGeom_ifc4.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4.lib
>   IfcGeom_ifc4x3_rc3.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x3_rc3.lib
>   IfcGeom_ifc4x2.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x2.lib
>   IfcGeom_ifc4x3_rc4.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom_ifc4x3_rc4.lib
>   IfcGeom.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\IfcGeom.lib
>   Serializers_ifc4x3_rc3.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x3_rc3.lib
>   Serializers_ifc4x3_rc2.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x3_rc2.lib
>   Serializers_ifc2x3.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc2x3.lib
>   Serializers_ifc4x3_rc4.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x3_rc4.lib
>   Serializers_ifc4x2.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x2.lib
>   Serializers_ifc4x3_rc1.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x3_rc1.lib
>   Serializers_ifc4x1.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4x1.lib
>   Serializers_ifc4.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers_ifc4.lib
>   Serializers.vcxproj -> C:\build\IfcOpenShell\_build-vs2019-x64\RelWithDebInfo\Serializers.lib
>   IfcPythonPYTHON_wrap.cxx
> C:\build\IfcOpenShell\_build-vs2019-x64\ifcwrap\CMakeFiles\_ifcopenshell_wrapper.dir\IfcPythonPYTHON_wrap.cxx(202,11): fatal error C1083: Não é possível abrir arquivo incluir: 'Python.h': No such file or direct
> ory [C:\build\IfcOpenShell\_build-vs2019-x64\ifcwrap\_ifcopenshell_wrapper.vcxproj]
> 
> x64 RelWithDebInfo IfcOpenShell installation failed

Any clue to solve this?

**Comment by aothms** [comment]
> pre-instalation of python

> Não é possível abrir arquivo incluir: 'Python.h': No such file or direct

How exactly did you configure the python paths?

Please next time open a new issue so that other users don't get unnecessary notifications and so that the issue can be better found by others.

Tbh the build script could be greatly improved for these cases, such as finding python installations from the windows registry.

**Comment by ricottatiago** [comment]
> > pre-instalation of python
> 
> > Não é possível abrir arquivo incluir: 'Python.h': No such file or direct
> 
> How exactly did you configure the python paths?
> 
> Please next time open a new issue so that other users don't get unnecessary notifications and so that the issue can be better found by others.
> 
> Tbh the build script could be greatly improved for these cases, such as finding python installations from the windows registry.

I am using the path to my user in the note C:\Users\user\AppData\Local\Programs\Python\Python310

Sorry, next time I will open a proper ticket :D

**Comment by aothms** [comment]
> I am using the path to my user in the note C:\Users\user\AppData\Local\Programs\Python\Python310

But where and how did you supply this to the build system?

Did you set `PY_VER_MAJOR_MINOR` and `PYTHONHOME` when you ran `run-cmake.bat`?

For us to understand the issue we need more detailed input on what actions were taken.

When you open `C:\build\IfcOpenShell_build-vs2019-x64\CMakeCache.txt` what entries are in there wrt to python?
