### ISSUE TITLE
Error when updating using the Update button - Archive size mismatch "bonsai", expected 87341658, was 87341636 

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5228]
I get this error `Archive size mismatch "bonsai", expected 87341658, was 87341636
`

I have installed 26th Aug version, trying to update to 27th August.

**Comment by Andrej730** [comment]
@BIMvoice can you please try again? It's likely you got in the middle of new build being uploaded to github - when build is uploaded to github but https://github.com/IfcOpenShell/blenderbim_unstable_repo/ is not yet updated because there are other builds in progress.

**Comment by BIMvoice** [comment]
@Andrej730 it worked, thank you!

But I keep getting this error every time I update. And it's just hanging and showing that loading cursor, until I crash Blender and restart it.

After restart I have the new version. I think it has something to do with admin rights on my PC. Could something be done about this? I'm guessing many users have to involve IT to undergo this one?

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1321, in modal
    self.exec_command_finish(canceled)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2789, in exec_command_finish
    _extensions_repo_refresh_on_change(
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 994, in _extensions_repo_refresh_on_change
    _extensions_repo_sync_wheels(repo_cache_store, extensions_enabled)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 985, in _extensions_repo_sync_wheels
    addon_utils._extension_sync_wheels(
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\addon_utils.py", line 1153, in _extension_sync_wheels
    apply_action(
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 361, in apply_action
    _rmtree_safe(filepath_abs, local_dir)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\_bpy_internal\extensions\wheel_manager.py", line 145, in _rmtree_safe
    shutil.rmtree(dir_remove)
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Ingen tilgang: 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd'
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 622, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\shutil.py", line 620, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Ingen tilgang: 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell\\_ifcopenshell_wrapper.cp311-win_amd64.pyd'
`

**Comment by Andrej730** [comment]
> But I keep getting this error every time I update. And it's just hanging and showing that loading cursor, until I crash Blender and restart it.
> 
> After restart I have the new version. I think it has something to do with admin rights on my PC. Could something be done about this? I'm guessing many users have to involve IT to undergo this one?

When do you see this error? It shows that error and then hangs? Or it shows that error and then hangs when you try to update again? Or ...?

The error traceback looks like upstream Blender issue that was present in Blender 4.2.0, you can try to update to Blender 4.2.1 where it was resolved.

**Comment by BIMvoice** [comment]
Let me update to 4.2.1 and check again tomorrow.

After I click on the update button I get the "thinking/loading" cursor. The error is shown in the background. Blender hands, the Extention window still up, until I restart it. Weirdly enough I can navigate through the menu, going to window and console to read the error.

Hopefully will go away after I update to 4.2.1.

**Comment by PCKK-koara** [comment]
When I tried to install a new daily version with Blender 4.2.1, I got a Report Error saying No module named 'ordered_set',. If it helps:)
![oredered_set](https://github.com/user-attachments/assets/d2911576-5674-46ac-82a4-3da46016904e)

**Comment by Andrej730** [comment]
> When I tried to install a new daily version with Blender 4.2.1, I got a Report Error saying No module named 'ordered_set',. If it helps:)

Hi! It's a separate issue, I've fixed in 1b49515, you can try the new daily build.

**Comment by Moult** [comment]
Is this still an issue?

**Comment by BIMvoice** [comment]
> Is this still an issue?

Yes @Moult , I still get this everyday I'm updating to daily build.

**Comment by brunopostle** [comment]
I saw this today. It went away after I clicked Repositories > Refresh remote.

I assume this is because the package updated in the time since Blender refreshed the repository metadata. Does the Bonsai download have the same filename if it is updated twice in the same day?

**Comment by Andrej730** [comment]
> PermissionError: [Errno 13] Permission denied: 'C:\\Users\\peco01\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\.local\\lib\\python3.11\\site-packages\\pyradiance\\libraycalls.so'

Any ideas how to reproduce this? Haven't seen those errors though updating unstable repo build daily.

> Does the Bonsai download have the same filename if it is updated twice in the same day?

Filename will be the same, we do not support multiple daily versions though different users may get different daily version depending when they will update Bonsai.

**Comment by Andrej730** [comment]
Archive mismatch issues fixed after 0e5008d
