### ISSUE TITLE
Option to copy Property name from Psets

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#5892]
Hey guys,

Sometimes it's handy to be able to select and copy the name of a property. Right now we can just copy the value of a property, when editing. And in general would be cool to be able to copy text for kind of any part of the UI, without having to edit stuff.

Not sure if this is possible, but I think many will find that useful.

What do you think?

**Comment by BIMvoice** [comment]
![Screenshot 2024-12-20 at 16 24 28](https://github.com/user-attachments/assets/9ba20979-77cd-47d3-9d46-a8b3f0a271d4)
@Andrej730  How in the world did you get that menu. I tried everything, this is what I get when I right click...

**Comment by Andrej730** [comment]
@BIMvoice open properties for editing.

**Comment by BIMvoice** [comment]
> @BIMvoice open properties for editing.

screenshot please, I tried that also in edit mode... I'm a noob ffs.

**Comment by Andrej730** [comment]
![image](https://github.com/user-attachments/assets/91b292fd-b24f-42f5-b808-003d014ea0de)

And then open context menu on the property.

**Comment by BIMvoice** [comment]
![Screenshot 2024-12-20 at 16 32 05](https://github.com/user-attachments/assets/39ce5c26-3432-434f-b16c-268161bed19c)


nothing like your menu, I right clicked everywhere.

**Comment by BIMvoice** [comment]
![Screenshot 2024-12-20 at 16 33 38](https://github.com/user-attachments/assets/fd220c4d-1242-4274-bb8b-03382de67626)

**Comment by BIMvoice** [comment]
![Screenshot 2024-12-20 at 16 36 00](https://github.com/user-attachments/assets/1700abd5-9dbd-442a-920d-7a01769477ce)

**Comment by BIMvoice** [comment]
@Andrej730  what am I doing wrong?

**Comment by Andrej730** [comment]
Are you sure you updated Bonsai after the commit above and not before? If before, Blender won't show you that update is available since Bonsai is using just a date for it's version, not including hour and minutes.

https://github.com/user-attachments/assets/38d37251-3748-4030-b84a-f78c42a2bbe1

**Comment by BIMvoice** [comment]
> Are you sure you updated Bonsai after the commit above and not before? If before, Blender won't show you that update is available since Bonsai is using just a date for it's version, not including hour and minutes.
> blender_9NRTKCgQE3.mp4

see in my previous image the version name in the bottom right corner. I don*t get anything when I refresh the repo manually...

@Andrej730  maybe it has something with the fact I'm on a mac?

**Comment by BIMvoice** [comment]
@Andrej730 I installed Blender 4.2.5 separately with the latest build and it's still not working. If you say it's working for you, it might be something Mac-specific.

**Comment by theoryshaw** [comment]
For the record i couldn't get this to work either. I'm on Windows. 

Recently added some functionality, that might help toward this end, however. 
https://community.osarch.org/discussion/comment/23305/#Comment_23305

**Comment by Andrej730** [comment]
Okay, I've installed Bonsai from the .zip and found there was a console error because I've forgot to commit a line of code. Should be fixed now.

```python
Traceback (most recent call last):
  File "\Blender\4.3\scripts\modules\bpy_types.py", line 1035, in draw_ls
    func(self, context)
  File "\Blender\4.3\extensions\.local\lib\python3.11\site-packages\bonsai\bim\ui.py", line 1153, in draw_custom_context_menu
    attr_name = attr.name
                ^^^^
NameError: name 'attr' is not defined
```

> Recently added some functionality, that might help toward this end, however.

That was my first idea too - to make it an operators with `emboss=False`. But it's messing with the alignment of the attribute name - it's making it centered along the button that's hidden.

**Comment by BIMvoice** [comment]
Still not working on my end on yesterday's build.

Merry Christmas :)

**Comment by Andrej730** [comment]
Merry Christmas!)

Just reinstalled Bonsai from the latest build and it does work for me. Please check system console for errors.
![image](https://github.com/user-attachments/assets/682ce99f-2878-4b12-903b-bb63b60f593c)

**Comment by BIMvoice** [comment]
> Merry Christmas!)
> 
> Just reinstalled Bonsai from the latest build and it does work for me. Please check system console for errors. ![image](https://private-user-images.githubusercontent.com/9417531/398523032-682ce99f-2878-4b12-903b-bb63b60f593c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDM2NjYsIm5iZiI6MTczNTIwMzM2NiwicGF0aCI6Ii85NDE3NTMxLzM5ODUyMzAzMi02ODJjZTk5Zi0yODc4LTRiMTItOTAzYi1iYjYzYjYwZjU5M2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDg1NjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU0MzM0ZDZmM2E4ZWVjN2M1YWIzMmRmZjFkZGIzMzI1ZTljZmYyZjUwYjE1ZWM3ZWZlNWM2YzkwYzRkYzI2ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.obmXS7rAfbW4yCzCLtlIkS-Vpk8zhdN26KMkF3Hg_pw)

@Andrej730 the unstable build is not updating, can you please fix that? That might be the explanation right now.

**Comment by Andrej730** [comment]
> the unstable build is not updating, can you please fix that? That might be the explanation right now.

Update didn't worked yesterday, commit with a fix was uploaded 3 days ago, so it's unrelated.

**Comment by BIMvoice** [comment]
I don't see any errors on my end, it just not work. Maybe we can do a screeshare sometime...

**Comment by BIMvoice** [comment]
Hi again @Andrej730 , happy new year! I have an update on this. This still does not work on my windows machine at work either. Is there anyone else except you who can confirm what you do works for them too?

**Comment by theoryshaw** [comment]
Confirmed. :)
...
I'm generally interested in putting 'stuff' in the context menu as well in BB.  That seems rarely used with BB, but, on the face of things, if doable, would seem to unlock another UI approach.

**Comment by BIMvoice** [comment]
@theoryshaw you confirm that you can copy that too? Or that it's not working? :D This is very strange then. What am I supposed to do if none of the machines I try it, it won't work?

**Comment by theoryshaw** [comment]
Sorry, yes, this still doesn't work for me either.

**Comment by Andrej730** [comment]
Totally forgot about this issue after celebrating the new year 😅

Was revisiting it just now and I think I've found why it was working for me and wasn't working for you - we were using this feature on different props. There was an issue preventing IFC Description and Copy Attribute Name from appearing for non-string properties. But it should be resolved now after https://github.com/IfcOpenShell/IfcOpenShell/commit/af81aa1fae85b6dfbeb31aec6c55aa32ba53b9b9

@theoryshaw @BIMvoice can you please try now to confirm it's fixed?

**Comment by BIMvoice** [comment]
It works now, on the latest Blender version + Bonsai unstable, thank you very much!

**Comment by theoryshaw** [comment]
works great... i like this new dabble into 'right clicking' and adding functionality in the context menu.  I think that UI approach in general should be explored more with Bonsai.
