### ISSUE TITLE
Have `bim.unassign_representation_item_style` remove the style of all the selected objects.

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#6525]
Would be nice if `bim.unassign_representation_item_style` removed the style of all the selected objects.

**Comment by BjornFidder** [comment]
Covered in issue [#6991](https://github.com/IfcOpenShell/IfcOpenShell/issues/6931) (and fixed in #6933.

**Comment by theoryshaw** [comment]
Hi, it wasn't really fixed yet.  Need to accomodate @Andrej730 comments... just need to get better at python first. ha.

**Comment by theoryshaw** [comment]
@BjornFidder Btw, if you want to run with addressing @Andrej730 please feel free. :)
