### ISSUE TITLE
Missing "IfcPostalAddress" from IfcSite and IfcBuilding entities Attributes

### ISSUE THREAD

**Issue by DimitriosThe** [IfcOpenShell/IfcOpenShell#6869]
### Bug Description

In IFC4_ADD2_TC1 according to [IfcPostalAddress ](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcactorresource/lexical/ifcpostaladdress.htm) should be an attribute within [IfcSite](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcproductextension/lexical/ifcsite.htm) and [IfcBuilding](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/schema/ifcproductextension/lexical/ifcbuilding.htm) , how ever in the edit attributes pane these fields do not appear.

IfcBuilding

![Image](https://github.com/user-attachments/assets/330e0186-2b7b-4d55-a61c-cf889cb9908e)

IfcSite

![Image](https://github.com/user-attachments/assets/b86f877b-071a-4a48-8929-e00987b20960)

Thank you,

### Debug and Error Output

```true

```

**Comment by sboddy** [comment]
The code for adding/editing IfcPostalAddress already exists, and can be seen by adding a stakeholder and adding an address. Probably a fairly simple task to add it to the site and building attribute sets. When someone gets to looking at that, the +/- buttons for AddressLines field do not dynamically add/remove lines like they should. You have to save the address, then re-edit before the AddressLines entries appear/disappear.

**Comment by Andrej730** [comment]
> When someone gets to looking at that, the +/- buttons for AddressLines field do not dynamically add/remove lines like they should. You have to save the address, then re-edit before the AddressLines entries appear/disappear.

@sboddy Can you please record a small demo to show the issue?

**Comment by sboddy** [comment]
https://github.com/user-attachments/assets/870036ae-0900-42a2-9653-5299f877ed75

**Comment by Andrej730** [comment]
Ahh, I see.  Thanks, will look into it.

**Comment by sboddy** [comment]
@Andrej730 I've just tested this, and I think we need to reopen.
Using the new explorer tool when adding "Address Lines", they do not get saved to the IfcPostalAddress line.

**Comment by Andrej730** [comment]
Was able to reproduce, I'll fix it.

**Comment by Andrej730** [comment]
Should be fixed now.

**Comment by sboddy** [comment]
Sorry, but nope.

In Project Overview -> Project Setup -> Explorer, I can add an IfcPostalAddress and the top level items work. AddressLines still do not work. I can add [+] an AddressLine, fill it in, but it is not saved to the IfcPostalAddress.

If I use the pop-up dialog using Object Information -> Object Metadata -> Attributes -> Edit, then click the Show Explorer UI icon, then [+] to add an address then _nothing_ is saved. I have to Use the [+] button. Then close that IfcPostalAddress by clicking "OK", reopen the pop-up, select the IfcPostalAddress, Edit it, then edit the desired fields, then click "OK".

So, after the initial faff around I can save the top level items, but like the Project Setup case, the AddressLines never get saved.

**Comment by Andrej730** [comment]
@sboddy 

> In Project Overview -> Project Setup -> Explorer, I can add an IfcPostalAddress and the top level items work. AddressLines still do not work. I can add [+] an AddressLine, fill it in, but it is not saved to the IfcPostalAddress.

Are you sure you're testing the latest commit?

https://github.com/user-attachments/assets/4628b078-0441-41a4-a69d-018da213017d

> If I use the pop-up dialog using Object Information -> Object Metadata -> Attributes -> Edit, then click the Show Explorer UI icon, then [+] to add an address then _nothing_ is saved.

Same as above, couldn't reproduce it.

https://github.com/user-attachments/assets/14542e62-9727-49c6-ba3b-30ff66dd963a

**Comment by sboddy** [comment]
I swear I updated! 😳 I blame those little green gremlins!

Sorry for the noise. Confirmed all is working well, including the AddressLines. I'll close this ticket now.
