### ISSUE TITLE
Bonsai - UI Bug - Snapping point offset from mouse pointer when using Measuring Tool

### ISSUE THREAD

**Issue by Tudjack** [IfcOpenShell/IfcOpenShell#7046]
### Bug Description

While using the Measuring Tool, snapping point is offset from the mouse pointer when in Orthographic View Mode.
But even in Perspective Mode, depending on the user's view point, it sometimes glitches.

**Comment by brunoperdigao** [comment]
Hi @Tudjack. I'm not being able to reproduce this issue. Do you have a specific file where this happens? Or do you have a step-by-step I can follow? If not, it could be useful if you can record a video of the issue. Thanks

**Comment by Tudjack** [comment]
![Image](https://github.com/user-attachments/assets/21f9a2cb-5b8a-48b6-a4cb-76d1a4976b84)

**Comment by Rmccornik** [comment]
Is there an option to add measuring locking option, when cursor snaps to the edge user presses A or shift+A to lock/save the Z direction of the edge to the Z direction of the measuring line? ...
Enabling following the Transformation Orientations for XYZ of the measurements (i.ex.: cursor directions) will also works fine. 

I often use measuring lines for temporary construction, such as window placement, which will help a lot.
Similar solution may be found in "Snap Line Tool" addon / "Make Lines" - but it does not follow Ifc edges 

Best Regards Rafał Karnicki

**Comment by theoryshaw** [comment]
No, not that i know of, but there's this, that might come in handy for you...

https://github.com/user-attachments/assets/24a879fd-b6a2-47bc-aded-c73269e2964e

**Comment by Rmccornik** [comment]
Thanks, :-)
Snapping problem appears when I have selected any object before. Deselecting helps in common, but interior measuring doesn't work well. I use a common blender measuring tool, and some add-ons help too.
Lately, I've discovered a useful combo for non-orthographic workflow: Snap Line Tool to build support constructions (snapping works well), and Construction Lines are worth too. 
The pain of designing lies mostly in the non-orthogonal working plane orientation,  so 3D Cursor Plus + Align 2 Custom combo works well. ;-) but this is for another topic. 
There is Blender snapping mess + Bonsai improvement, sometimes they interfere with each other.

**Comment by Tudjack** [comment]
I think the problem lays on view scale/ view rotation and orthographic/perspective view settings. The bug is somewhere in there. :)

**Comment by brunoperdigao** [comment]
@Tudjack I pushed a commit that should be available in the next release. Please test and let me know if you notice any improvements.

**Comment by Rmccornik** [comment]
The problem with snapping seems quite common. When it appears I unselect all AA. Change view position (set fov to 18 helps too - closer camera distance/observation point) if still don’t work - isolate object.
So, I think that problem lays in objects we do not see but blender snapping not ignores them. Section planes causes troubles in this situation too.

**Comment by brunoperdigao** [comment]
I’ve made a few more improvements:
- Points hidden by the clipping planes are now ignored.
- The focal‑length issue shall be solved.

Please let me know if you notice any further issues.

**Comment by Rmccornik** [comment]
We get a trip longer than anyone supposed to be ;-). For first glance it works... (B 20250925), but measuring lines ignores geometry behind the clipping plane, and points are lying somewhere in the background. 
What worse,  latest Bonsai does not work with properly with B4.5LTS. - "Wall issue"   
I go for tests.

Best Regards 
RK

ps. 
Measuring tool is going to be great construction supporting tool soon :-D (We hope)

**Comment by Tudjack** [comment]
Unfortunately I had no time to test it yet. The alpha builds automatic updates are still not working and I did not want to break my current installation.

**Comment by Tudjack** [comment]
What I discovered previously, if I have an Ifc model which has the local coordinates very far from 0,0 then they (the measuring tool snaps) definitely don't work properly. It doesn't matter if it's orthographic or perspective view.

**Comment by Rmccornik** [comment]
> What I discovered previously, if I have an Ifc model which has the local coordinates very far from 0,0 then they (the measuring tool snaps) definitely don't work properly. It doesn't matter if it's orthographic or perspective view.

- Bonsai 20250927 works fine (B4.5.4)
- Range of Blender snapping precision issues is a long story, common solution:
           - Do not use clipping planes, 
           - Change camera position
           - Deselecting helps,  press "AA",  
           - At the view side tab set a higher "clipping plane" value,

RK

**Comment by Tudjack** [comment]
Just tested the new update and unfortunately the snaps are still not working properly.
I think it's because of the models we operate on at work are very far away from 0,0.
It's the only explanation I have at the moment.
Something to do with the view extents in Blender I guess.


![Image](https://github.com/user-attachments/assets/f7eb4fd6-8f2d-411b-b1ef-52490d7c4b8a)

**Comment by Rmccornik** [comment]
Well, my investigation gives me some clues.
- You use orto view - so it is easy to fly away with the point of view - the distance matters. - It is better to use a perspective view - it is easier to manage.
- Clip start and End values (View side panel) have a serious impact on the behaviour of the tool. 
 
 I use 10cm for near clipping and 100m for End value. (try to set End to 100km - 👹 - In my opinion, there is a problem with rounding and comparing values - typical Excel issue. 

It happens in regular Blender snapping, too. :-(  

I got another bug while support construction on non non-perpendicular Wall. 3 steps without drawing interruption - continuous line.
1. Draw a measurement alongthe  vertical edge of the wall,
2.  Limit (shift+Z) to xy axis to draw horizontal line aligned to the surface.
3.  Try to limit the direction to the Z axis - causes tool fails, and snapping does not work anymore.

5. ESC, shift M, ESC allows to restart the masuring tool.

Best regards RK

**Comment by Tudjack** [comment]
I switched to perspective view as well (not shown in the video), it is a little better but still hard to snap. 
Basically the pointer of your mouse has an offset to the point you want to snap to.
I tried everything, from locking the axes, selecting, deselecting, restarting the tool etc. It doesn't matter, the problem is that UI pointer offset.

**Comment by brunoperdigao** [comment]
@Tudjack the problem is very likely the distance from origin. I identified that some calculations for the snapping system are not performing well for large distances. I'm already working on it. Hopefully we'll have a solution soon.

**Comment by brunoperdigao** [comment]
@Tudjack could you test the snaps again after this [commit](https://github.com/IfcOpenShell/IfcOpenShell/commit/300855276f0e94d07f1b7214261f4f1e1e0c0608)? It should address the problem with objects too far from origin.

**Comment by Tudjack** [comment]
Just installed the latest alpha build on Blender 5.0, it's working fine now.
I will test it tomorrow on another machine at work and notify if any issues.
Thanks for the hard work!

**Comment by BIMvoice** [comment]
This looks resolved on current v0.8.0, and the reporter already confirmed it working on 2025-11-20. The snap offset was a floating point precision loss in the mouse to 3D projection, worst far from the origin and in orthographic view. It is now handled by numpy float64 versions of the projection functions in tool/cad.py (region_2d_to_vector_3d_np and its companions) plus an orthographic far clip clamp, and the measure tool snap ray uses them in tool/raycast.py. Since the behaviour is confirmed fixed, I think this can be closed, please reopen with a sample if the offset returns.
