### ISSUE TITLE
`bim.calculate_single_quantity()` seems to change the multiple entities even though 1 object was selected

### ISSUE THREAD

**Issue by theoryshaw** [IfcOpenShell/IfcOpenShell#7304]
### Bug Description

If you try and print `LIFE SAFETY PLAN - MEZZANINE`, it throws the following error. 

I feel this file may have been corrupted by https://github.com/IfcOpenShell/IfcOpenShell/pull/7301
Could be wrong. 

file: https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/3e7c3226b9bc5868524f483e530bc62f6e2c6d31

### Debug and Error Output

```true
Python: Traceback (most recent call last):
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 350, in execute
    linework_svg = self.generate_linework(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 912, in generate_linework
    self.serialize_contexts_elements(ifc, tree, contexts, "body", drawing_elements, target_view)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\bonsai\bim\module\drawing\operator.py", line 590, in serialize_contexts_elements
    self.serialiser.write(elem)
  File "C:\Users\Ryan Schultz\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\.local\lib\python3.11\site-packages\ifcopenshell\ifcopenshell_wrapper.py", line 4416, in write
    return _ifcopenshell_wrapper.SvgSerializer_write(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HasProperties not found on IfcElementQuantity
```

**Comment by theoryshaw** [comment]
The following is the diff between the last working ifc save, and the one that didn't work.

https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/1971102285d09ddaa8f2e8e12c6339db4de00311

**Comment by theoryshaw** [comment]
So, i don't think it was related to https://github.com/IfcOpenShell/IfcOpenShell/pull/7301

...

- So i [reverted back](https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/2fc6a44a9120675cc05c7ff51b3a090b52f2c490) to the last time the file worked. 
- I selected  `GlobalId = "1mBCiaPS92ogSWydi1WuDe"` which was an IfcBeam
- I then changed it to an IfcElementProxy
- I deleted all the old beam psets. 
- then i ran `bim.calculate_single_quantity()`. 

<img width="280" height="133" alt="Image" src="https://github.com/user-attachments/assets/1becf23c-9140-4acf-b29d-3ad240ecc77e" />
- And then i tried to print, and got the error mentioned. 

Here's the diff after this exercise. 
https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/b2b3d1ed9a2821a2dc744ed808b8c1a5dccec03b

**Comment by theoryshaw** [comment]
It's even simpler...


- So i [reverted back](https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/2fc6a44a9120675cc05c7ff51b3a090b52f2c490) to the last time the file worked. 
- I selected  `GlobalId = "1mBCiaPS92ogSWydi1WuDe"` which was an IfcBeam
- then i ran `bim.calculate_single_quantity()`. 

<img width="280" height="133" alt="Image" src="https://github.com/user-attachments/assets/1becf23c-9140-4acf-b29d-3ad240ecc77e" />
- And then i tried to print, and got the error mentioned.

**Comment by theoryshaw** [comment]
Here's the diff on that last troubleshoot. 
https://hub.openingdesign.com/OpeningDesign/Cool_Car_Guys/commit/de6e2381aed40c62bfcf43a0edd4bdb9db3dff09

It seems like it recalculating the quantities on a lot of objects. 
At the time, only one object was selected.

**Comment by theoryshaw** [comment]
I think this problem is related to: https://github.com/IfcOpenShell/IfcOpenShell/pull/7126/files

The commit before, i didn't have the error.

**Comment by aothms** [comment]
> RuntimeError: HasProperties not found on IfcElementQuantity

That's a very clear message. I think my commit should fix that.

**Comment by theoryshaw** [comment]
Thanks @aothms , unfortunately that did not fix it. 

I think the part of the root cause is that something in [this](https://github.com/IfcOpenShell/IfcOpenShell/pull/7126/files) commit is causing the recalculation of multiple  `IFCELEMENTQUANTITY` entities when `bim.calculate_single_quantity()` is run. 
From my test [this](https://github.com/IfcOpenShell/IfcOpenShell/pull/7301/commits/ca382f47df0c7c468c7b60ad1c0af71d5e390779) commit fixes it, but defer to you on final assessment.

**Comment by theoryshaw** [comment]
closed with https://github.com/IfcOpenShell/IfcOpenShell/pull/7301/
